//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyDuty.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DailyDuty.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercising the Right.
        /// </summary>
        internal static string ChallengeLog_Commendation {
            get {
                return ResourceManager.GetString("ChallengeLog_Commendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Exercising the Right&apos; Warning.
        /// </summary>
        internal static string ChallengeLog_CommendationLabel {
            get {
                return ResourceManager.GetString("ChallengeLog_CommendationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commendations Remaining.
        /// </summary>
        internal static string ChallengeLog_CommendationsRemaining {
            get {
                return ResourceManager.GetString("ChallengeLog_CommendationsRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dungeon Master.
        /// </summary>
        internal static string ChallengeLog_DungeonMaster {
            get {
                return ResourceManager.GetString("ChallengeLog_DungeonMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Dungeon Master&apos; Warning.
        /// </summary>
        internal static string ChallengeLog_DungeonMasterLabel {
            get {
                return ResourceManager.GetString("ChallengeLog_DungeonMasterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dungeons Remaining.
        /// </summary>
        internal static string ChallengeLog_DungeonMasterRemaining {
            get {
                return ResourceManager.GetString("ChallengeLog_DungeonMasterRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeling Lucky.
        /// </summary>
        internal static string ChallengeLog_DungeonRoulette {
            get {
                return ResourceManager.GetString("ChallengeLog_DungeonRoulette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Feeling Lucky&apos; Warning.
        /// </summary>
        internal static string ChallengeLog_DungeonRouletteLabel {
            get {
                return ResourceManager.GetString("ChallengeLog_DungeonRouletteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dungeon Roulettes Remaining.
        /// </summary>
        internal static string ChallengeLog_DungeonRoulettesRemaining {
            get {
                return ResourceManager.GetString("ChallengeLog_DungeonRoulettesRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge Log.
        /// </summary>
        internal static string ChallengeLog_Label {
            get {
                return ResourceManager.GetString("ChallengeLog_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Timers Overlay.
        /// </summary>
        internal static string Commands_Timers_DisableOverlay {
            get {
                return ResourceManager.GetString("Commands_Timers_DisableOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Timers Overlay.
        /// </summary>
        internal static string Commands_Timers_EnableOverlay {
            get {
                return ResourceManager.GetString("Commands_Timers_EnableOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Timers Overlay.
        /// </summary>
        internal static string Commands_Timers_EnablingDisabling {
            get {
                return ResourceManager.GetString("Commands_Timers_EnablingDisabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Timers Overlay.
        /// </summary>
        internal static string Commands_Timers_ToggleOverlay {
            get {
                return ResourceManager.GetString("Commands_Timers_ToggleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Todo Overlay.
        /// </summary>
        internal static string Commands_Todo_DisableOverlay {
            get {
                return ResourceManager.GetString("Commands_Todo_DisableOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Todo Overlay.
        /// </summary>
        internal static string Commands_Todo_EnableOverlay {
            get {
                return ResourceManager.GetString("Commands_Todo_EnableOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Todo Overlay.
        /// </summary>
        internal static string Commands_Todo_EnablingDisabling {
            get {
                return ResourceManager.GetString("Commands_Todo_EnablingDisabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-display todo tasks in chat.
        /// </summary>
        internal static string Commands_Todo_RepeatMessages {
            get {
                return ResourceManager.GetString("Commands_Todo_RepeatMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Todo Overlay.
        /// </summary>
        internal static string Commands_Todo_ToggleOverlay {
            get {
                return ResourceManager.GetString("Commands_Todo_ToggleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        internal static string Common_Accepted {
            get {
                return ResourceManager.GetString("Common_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Common_All {
            get {
                return ResourceManager.GetString("Common_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowances.
        /// </summary>
        internal static string Common_Allowances {
            get {
                return ResourceManager.GetString("Common_Allowances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowances Available.
        /// </summary>
        internal static string Common_AllowancesAvailable {
            get {
                return ResourceManager.GetString("Common_AllowancesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowances Remaining.
        /// </summary>
        internal static string Common_AllowancesRemaining {
            get {
                return ResourceManager.GetString("Common_AllowancesRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabetical.
        /// </summary>
        internal static string Common_Alphabetical {
            get {
                return ResourceManager.GetString("Common_Alphabetical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Resize.
        /// </summary>
        internal static string Common_AutoResize {
            get {
                return ResourceManager.GetString("Common_AutoResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Now.
        /// </summary>
        internal static string Common_AvailableNow {
            get {
                return ResourceManager.GetString("Common_AvailableNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string Common_Background {
            get {
                return ResourceManager.GetString("Common_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle.
        /// </summary>
        internal static string Common_Battle {
            get {
                return ResourceManager.GetString("Common_Battle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Left.
        /// </summary>
        internal static string Common_BottomLeft {
            get {
                return ResourceManager.GetString("Common_BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Right.
        /// </summary>
        internal static string Common_BottomRight {
            get {
                return ResourceManager.GetString("Common_BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clickable Link.
        /// </summary>
        internal static string Common_ClickableLink {
            get {
                return ResourceManager.GetString("Common_ClickableLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        internal static string Common_Command {
            get {
                return ResourceManager.GetString("Common_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string Common_Complete {
            get {
                return ResourceManager.GetString("Common_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completions.
        /// </summary>
        internal static string Common_Completions {
            get {
                return ResourceManager.GetString("Common_Completions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Tasks.
        /// </summary>
        internal static string Common_DailyTasks {
            get {
                return ResourceManager.GetString("Common_DailyTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Common_Default {
            get {
                return ResourceManager.GetString("Common_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string Common_Descending {
            get {
                return ResourceManager.GetString("Common_Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Common_Disabled {
            get {
                return ResourceManager.GetString("Common_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling.
        /// </summary>
        internal static string Common_Disabling {
            get {
                return ResourceManager.GetString("Common_Disabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drops.
        /// </summary>
        internal static string Common_Drops {
            get {
                return ResourceManager.GetString("Common_Drops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Common_Enabled {
            get {
                return ResourceManager.GetString("Common_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling.
        /// </summary>
        internal static string Common_Enabling {
            get {
                return ResourceManager.GetString("Common_Enabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal To.
        /// </summary>
        internal static string Common_Equal {
            get {
                return ResourceManager.GetString("Common_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground.
        /// </summary>
        internal static string Common_Foreground {
            get {
                return ResourceManager.GetString("Common_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        internal static string Common_Header {
            get {
                return ResourceManager.GetString("Common_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Completed Tasks.
        /// </summary>
        internal static string Common_HideCompletedTasks {
            get {
                return ResourceManager.GetString("Common_HideCompletedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Window In Duty.
        /// </summary>
        internal static string Common_HideInDuty {
            get {
                return ResourceManager.GetString("Common_HideInDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Window When Complete.
        /// </summary>
        internal static string Common_HideWhenComplete {
            get {
                return ResourceManager.GetString("Common_HideWhenComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete.
        /// </summary>
        internal static string Common_Incomplete {
            get {
                return ResourceManager.GetString("Common_Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Than.
        /// </summary>
        internal static string Common_LessThan {
            get {
                return ResourceManager.GetString("Common_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Than or Equal To.
        /// </summary>
        internal static string Common_LessThanEqual {
            get {
                return ResourceManager.GetString("Common_LessThanEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Window Position.
        /// </summary>
        internal static string Common_LockWindowPosition {
            get {
                return ResourceManager.GetString("Common_LockWindowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Options.
        /// </summary>
        internal static string Common_MainOptions {
            get {
                return ResourceManager.GetString("Common_MainOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone Change notifications will only appear once every five minutes
        ///This is to prevent excessive chatlog spamming.
        /// </summary>
        internal static string Common_MessageTimeout_Info {
            get {
                return ResourceManager.GetString("Common_MessageTimeout_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string Common_Mode {
            get {
                return ResourceManager.GetString("Common_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Reset.
        /// </summary>
        internal static string Common_NextReset {
            get {
                return ResourceManager.GetString("Common_NextReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string Common_Opacity {
            get {
                return ResourceManager.GetString("Common_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overriden.
        /// </summary>
        internal static string Common_Overriden {
            get {
                return ResourceManager.GetString("Common_Overriden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Time.
        /// </summary>
        internal static string Common_RemainingTime {
            get {
                return ResourceManager.GetString("Common_RemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Default.
        /// </summary>
        internal static string Common_Reset {
            get {
                return ResourceManager.GetString("Common_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        internal static string Common_Single {
            get {
                return ResourceManager.GetString("Common_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamps.
        /// </summary>
        internal static string Common_Stamps {
            get {
                return ResourceManager.GetString("Common_Stamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppressed.
        /// </summary>
        internal static string Common_Suppressed {
            get {
                return ResourceManager.GetString("Common_Suppressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string Common_Target {
            get {
                return ResourceManager.GetString("Common_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Selection.
        /// </summary>
        internal static string Common_TaskSelection {
            get {
                return ResourceManager.GetString("Common_TaskSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Common_Text {
            get {
                return ResourceManager.GetString("Common_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Common_Time {
            get {
                return ResourceManager.GetString("Common_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Left.
        /// </summary>
        internal static string Common_TopLeft {
            get {
                return ResourceManager.GetString("Common_TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Right.
        /// </summary>
        internal static string Common_TopRight {
            get {
                return ResourceManager.GetString("Common_TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        internal static string Common_Unavailable {
            get {
                return ResourceManager.GetString("Common_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Common_Unknown {
            get {
                return ResourceManager.GetString("Common_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Tasks.
        /// </summary>
        internal static string Common_WeeklyTasks {
            get {
                return ResourceManager.GetString("Common_WeeklyTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Options.
        /// </summary>
        internal static string Common_WindowOptions {
            get {
                return ResourceManager.GetString("Common_WindowOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Disabled.
        /// </summary>
        internal static string Config_HideDisabled {
            get {
                return ResourceManager.GetString("Config_HideDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Config_Label {
            get {
                return ResourceManager.GetString("Config_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Notification on Login.
        /// </summary>
        internal static string Config_LoginNotification {
            get {
                return ResourceManager.GetString("Config_LoginNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Complete When.
        /// </summary>
        internal static string Config_MarkCompleteWhen {
            get {
                return ResourceManager.GetString("Config_MarkCompleteWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Options.
        /// </summary>
        internal static string Config_NotificationOptions {
            get {
                return ResourceManager.GetString("Config_NotificationOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Config_Options {
            get {
                return ResourceManager.GetString("Config_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Disabled.
        /// </summary>
        internal static string Config_ShowDisabled {
            get {
                return ResourceManager.GetString("Config_ShowDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Notification on Zone Change.
        /// </summary>
        internal static string Config_ZoneChageNotification {
            get {
                return ResourceManager.GetString("Config_ZoneChageNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Delivery.
        /// </summary>
        internal static string CustomDelivery_Label {
            get {
                return ResourceManager.GetString("CustomDelivery_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Shift + Control while clicking.
        /// </summary>
        internal static string DisabledButton_Hover {
            get {
                return ResourceManager.GetString("DisabledButton_Hover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget Remaining.
        /// </summary>
        internal static string DomanEnclave_BudgetRemaining {
            get {
                return ResourceManager.GetString("DomanEnclave_BudgetRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications can be clicked on to teleport to the Doman Enclave.
        /// </summary>
        internal static string DomanEnclave_ClickableLink {
            get {
                return ResourceManager.GetString("DomanEnclave_ClickableLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Allowance.
        /// </summary>
        internal static string DomanEnclave_CurrentAllowance {
            get {
                return ResourceManager.GetString("DomanEnclave_CurrentAllowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gil Remaining.
        /// </summary>
        internal static string DomanEnclave_GilRemaining {
            get {
                return ResourceManager.GetString("DomanEnclave_GilRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doman Enclave.
        /// </summary>
        internal static string DomanEnclave_Label {
            get {
                return ResourceManager.GetString("DomanEnclave_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Unknown.
        /// </summary>
        internal static string DomanEnclave_StatusUnknown {
            get {
                return ResourceManager.GetString("DomanEnclave_StatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status unknown, visit the Doman Enclave to initialize module.
        /// </summary>
        internal static string DomanEnclave_StatusUnknown_Info {
            get {
                return ResourceManager.GetString("DomanEnclave_StatusUnknown_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications can be clicked on to open the Duty Finder.
        /// </summary>
        internal static string DutyFinder_ClickableLink {
            get {
                return ResourceManager.GetString("DutyFinder_ClickableLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Finder Overlay.
        /// </summary>
        internal static string DutyFinder_Overlay {
            get {
                return ResourceManager.GetString("DutyFinder_Overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete When Tomecapped.
        /// </summary>
        internal static string DutyRoulette_CompleteWhenCapped {
            get {
                return ResourceManager.GetString("DutyRoulette_CompleteWhenCapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks Duty Roulette Module as complete when you are at your weekly tomestone cap.
        /// </summary>
        internal static string DutyRoulette_CompleteWhenCapped_Info {
            get {
                return ResourceManager.GetString("DutyRoulette_CompleteWhenCapped_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Complete.
        /// </summary>
        internal static string DutyRoulette_DutyComplete {
            get {
                return ResourceManager.GetString("DutyRoulette_DutyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Incomplete.
        /// </summary>
        internal static string DutyRoulette_DutyIncomplete {
            get {
                return ResourceManager.GetString("DutyRoulette_DutyIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert Roulette Feature.
        /// </summary>
        internal static string DutyRoulette_ExpertFeature {
            get {
                return ResourceManager.GetString("DutyRoulette_ExpertFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks the Expert Roulette as overriden when you are at your weekly tomestone cap.
        /// </summary>
        internal static string DutyRoulette_ExpertFeature_Info {
            get {
                return ResourceManager.GetString("DutyRoulette_ExpertFeature_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert Tomestones.
        /// </summary>
        internal static string DutyRoulette_ExpertTomestones {
            get {
                return ResourceManager.GetString("DutyRoulette_ExpertTomestones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Roulette.
        /// </summary>
        internal static string DutyRoulette_Label {
            get {
                return ResourceManager.GetString("DutyRoulette_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No roulettes have been selected for tracking.
        /// </summary>
        internal static string DutyRoulette_NothingTracked {
            get {
                return ResourceManager.GetString("DutyRoulette_NothingTracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Override.
        /// </summary>
        internal static string DutyRoulette_Override {
            get {
                return ResourceManager.GetString("DutyRoulette_Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roulettes Remaining.
        /// </summary>
        internal static string DutyRoulette_Remaining {
            get {
                return ResourceManager.GetString("DutyRoulette_Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Roulettes to Track.
        /// </summary>
        internal static string DutyRoulette_RouletteSelection {
            get {
                return ResourceManager.GetString("DutyRoulette_RouletteSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roulette Status.
        /// </summary>
        internal static string DutyRoulette_Status {
            get {
                return ResourceManager.GetString("DutyRoulette_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endwalker.
        /// </summary>
        internal static string Expansion_Endwalker {
            get {
                return ResourceManager.GetString("Expansion_Endwalker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavensward.
        /// </summary>
        internal static string Expansion_Heavensward {
            get {
                return ResourceManager.GetString("Expansion_Heavensward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Realm Reborn.
        /// </summary>
        internal static string Expansion_RealmReborn {
            get {
                return ResourceManager.GetString("Expansion_RealmReborn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadowbringers.
        /// </summary>
        internal static string Expansion_Shadowbringers {
            get {
                return ResourceManager.GetString("Expansion_Shadowbringers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stormblood.
        /// </summary>
        internal static string Expansion_Stormblood {
            get {
                return ResourceManager.GetString("Expansion_Stormblood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify if any allowances remain this week, the highest score is below 80 and Fashion Report is available for turn-in.
        /// </summary>
        internal static string FashionReport_80Mode_Info {
            get {
                return ResourceManager.GetString("FashionReport_80Mode_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify if any allowances remain this week and fashion report is available for turn-in.
        /// </summary>
        internal static string FashionReport_AllMode_Info {
            get {
                return ResourceManager.GetString("FashionReport_AllMode_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowances Available.
        /// </summary>
        internal static string FashionReport_AllowancesAvailable {
            get {
                return ResourceManager.GetString("FashionReport_AllowancesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Condition.
        /// </summary>
        internal static string FashionReport_CompletionCondition {
            get {
                return ResourceManager.GetString("FashionReport_CompletionCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Score.
        /// </summary>
        internal static string FashionReport_HighestScore {
            get {
                return ResourceManager.GetString("FashionReport_HighestScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fashion Report.
        /// </summary>
        internal static string FashionReport_Label {
            get {
                return ResourceManager.GetString("FashionReport_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80 Plus.
        /// </summary>
        internal static string FashionReport_Mode80Plus {
            get {
                return ResourceManager.GetString("FashionReport_Mode80Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Open.
        /// </summary>
        internal static string FashionReport_ReportOpen {
            get {
                return ResourceManager.GetString("FashionReport_ReportOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only notify if no allowances have been spent this week and Fashion Report is available for turn-in.
        /// </summary>
        internal static string FashionReport_SingleMode_Info {
            get {
                return ResourceManager.GetString("FashionReport_SingleMode_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faux Hollows.
        /// </summary>
        internal static string FauxHollows_Label {
            get {
                return ResourceManager.GetString("FauxHollows_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Retelling.
        /// </summary>
        internal static string FauxHollows_Retelling {
            get {
                return ResourceManager.GetString("FauxHollows_Retelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require completing retelling to mark module as complete.
        /// </summary>
        internal static string FauxHollows_Retelling_Info {
            get {
                return ResourceManager.GetString("FauxHollows_Retelling_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreal Trial Available.
        /// </summary>
        internal static string FauxHollows_TrialAvailable {
            get {
                return ResourceManager.GetString("FauxHollows_TrialAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications can be clicked on to teleport to the Gold Saucer.
        /// </summary>
        internal static string GoldSaucer_ClickableLink {
            get {
                return ResourceManager.GetString("GoldSaucer_ClickableLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Available.
        /// </summary>
        internal static string GrandCompany_MissionAvailable {
            get {
                return ResourceManager.GetString("GrandCompany_MissionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No jobs have been selected for tracking.
        /// </summary>
        internal static string GrandCompany_NothingTracked {
            get {
                return ResourceManager.GetString("GrandCompany_NothingTracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Company (Provision).
        /// </summary>
        internal static string GrandCompany_ProvisioningLabel {
            get {
                return ResourceManager.GetString("GrandCompany_ProvisioningLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Company (Squadron).
        /// </summary>
        internal static string GrandCompany_SquadronLabel {
            get {
                return ResourceManager.GetString("GrandCompany_SquadronLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Company (Supply).
        /// </summary>
        internal static string GrandCompany_SupplyLabel {
            get {
                return ResourceManager.GetString("GrandCompany_SupplyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracked Jobs.
        /// </summary>
        internal static string GrandCompany_Tracked {
            get {
                return ResourceManager.GetString("GrandCompany_Tracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunt Marks (Daily).
        /// </summary>
        internal static string HuntMarks_DailyLabel {
            get {
                return ResourceManager.GetString("HuntMarks_DailyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elite.
        /// </summary>
        internal static string HuntMarks_Elite {
            get {
                return ResourceManager.GetString("HuntMarks_Elite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Complete.
        /// </summary>
        internal static string HuntMarks_ForceComplete {
            get {
                return ResourceManager.GetString("HuntMarks_ForceComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override module status and mark complete.
        /// </summary>
        internal static string HuntMarks_ForceComplete_Info {
            get {
                return ResourceManager.GetString("HuntMarks_ForceComplete_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action cannot be undone.
        /// </summary>
        internal static string HuntMarks_ForceComplete_Warning {
            get {
                return ResourceManager.GetString("HuntMarks_ForceComplete_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killed.
        /// </summary>
        internal static string HuntMarks_Killed {
            get {
                return ResourceManager.GetString("HuntMarks_Killed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level One.
        /// </summary>
        internal static string HuntMarks_LevelOne {
            get {
                return ResourceManager.GetString("HuntMarks_LevelOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Three.
        /// </summary>
        internal static string HuntMarks_LevelThree {
            get {
                return ResourceManager.GetString("HuntMarks_LevelThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Two.
        /// </summary>
        internal static string HuntMarks_LevelTwo {
            get {
                return ResourceManager.GetString("HuntMarks_LevelTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hunts have been selected for tracking.
        /// </summary>
        internal static string HuntMarks_NothingTracked {
            get {
                return ResourceManager.GetString("HuntMarks_NothingTracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained.
        /// </summary>
        internal static string HuntMarks_Obtained {
            get {
                return ResourceManager.GetString("HuntMarks_Obtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunts Remaining.
        /// </summary>
        internal static string HuntMarks_Remaining {
            get {
                return ResourceManager.GetString("HuntMarks_Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracked Hunts Status.
        /// </summary>
        internal static string HuntMarks_Status {
            get {
                return ResourceManager.GetString("HuntMarks_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracked Hunts.
        /// </summary>
        internal static string HuntMarks_Tracked {
            get {
                return ResourceManager.GetString("HuntMarks_Tracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unobtained.
        /// </summary>
        internal static string HuntMarks_Unobtained {
            get {
                return ResourceManager.GetString("HuntMarks_Unobtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunt Marks (Weekly).
        /// </summary>
        internal static string HuntMarks_WeeklyLabel {
            get {
                return ResourceManager.GetString("HuntMarks_WeeklyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumbo Cactpot.
        /// </summary>
        internal static string JumboCactpot_Label {
            get {
                return ResourceManager.GetString("JumboCactpot_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Drawing.
        /// </summary>
        internal static string JumboCactpot_NextDrawing {
            get {
                return ResourceManager.GetString("JumboCactpot_NextDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Tickets.
        /// </summary>
        internal static string JumboCactpot_NoTickets {
            get {
                return ResourceManager.GetString("JumboCactpot_NoTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        internal static string JumboCactpot_Tickets {
            get {
                return ResourceManager.GetString("JumboCactpot_Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets Available.
        /// </summary>
        internal static string JumboCactpot_TicketsAvailable {
            get {
                return ResourceManager.GetString("JumboCactpot_TicketsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levequest.
        /// </summary>
        internal static string Levequest_Label {
            get {
                return ResourceManager.GetString("Levequest_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Allowance.
        /// </summary>
        internal static string Levequest_NextAllowance {
            get {
                return ResourceManager.GetString("Levequest_NextAllowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string MaskedCarnivale_Advanced {
            get {
                return ResourceManager.GetString("MaskedCarnivale_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masked Carnivale.
        /// </summary>
        internal static string MaskedCarnivale_Label {
            get {
                return ResourceManager.GetString("MaskedCarnivale_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate.
        /// </summary>
        internal static string MaskedCarnivale_Moderate {
            get {
                return ResourceManager.GetString("MaskedCarnivale_Moderate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Tasks Tracked.
        /// </summary>
        internal static string MaskedCarnivale_NothingTracked {
            get {
                return ResourceManager.GetString("MaskedCarnivale_NothingTracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novice.
        /// </summary>
        internal static string MaskedCarnivale_Novice {
            get {
                return ResourceManager.GetString("MaskedCarnivale_Novice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini Cactpot.
        /// </summary>
        internal static string MiniCactpot_Label {
            get {
                return ResourceManager.GetString("MiniCactpot_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets Remaining.
        /// </summary>
        internal static string MiniCactpot_TicketsRemaining {
            get {
                return ResourceManager.GetString("MiniCactpot_TicketsRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications can be clicked on to open the Party Finder.
        /// </summary>
        internal static string PartyFinder_ClickableLink {
            get {
                return ResourceManager.GetString("PartyFinder_ClickableLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raids (Alliance).
        /// </summary>
        internal static string Raids_AllianceLabel {
            get {
                return ResourceManager.GetString("Raids_AllianceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raids (Normal).
        /// </summary>
        internal static string Raids_NormalLabel {
            get {
                return ResourceManager.GetString("Raids_NormalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No raids have been selected for tracking.
        /// </summary>
        internal static string Raids_NothingTracked {
            get {
                return ResourceManager.GetString("Raids_NothingTracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raid Remaining.
        /// </summary>
        internal static string Raids_RaidRemaining {
            get {
                return ResourceManager.GetString("Raids_RaidRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raids Remaining.
        /// </summary>
        internal static string Raids_RaidsRemaining {
            get {
                return ResourceManager.GetString("Raids_RaidsRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Tracked Raids.
        /// </summary>
        internal static string Raids_Regenerate {
            get {
                return ResourceManager.GetString("Raids_Regenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload duty information, and reset settings.
        /// </summary>
        internal static string Raids_Regenerate_Info {
            get {
                return ResourceManager.GetString("Raids_Regenerate_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracked Raids.
        /// </summary>
        internal static string Raids_TrackedRaids {
            get {
                return ResourceManager.GetString("Raids_TrackedRaids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status_Label {
            get {
                return ResourceManager.GetString("Status_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Status.
        /// </summary>
        internal static string Status_ModuleStatus {
            get {
                return ResourceManager.GetString("Status_ModuleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snooze.
        /// </summary>
        internal static string Status_Snooze {
            get {
                return ResourceManager.GetString("Status_Snooze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression.
        /// </summary>
        internal static string Status_Suppression {
            get {
                return ResourceManager.GetString("Status_Suppression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppress notifications until next reset.
        /// </summary>
        internal static string Status_Suppression_Info {
            get {
                return ResourceManager.GetString("Status_Suppression_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnSnooze.
        /// </summary>
        internal static string Status_Unsnooze {
            get {
                return ResourceManager.GetString("Status_Unsnooze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Options.
        /// </summary>
        internal static string Timers_ColorOptions {
            get {
                return ResourceManager.GetString("Timers_ColorOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day, {1} hours.
        /// </summary>
        internal static string Timers_DayPlusHours {
            get {
                return ResourceManager.GetString("Timers_DayPlusHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        internal static string Timers_DisplayName {
            get {
                return ResourceManager.GetString("Timers_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Style.
        /// </summary>
        internal static string Timers_EditStyle {
            get {
                return ResourceManager.GetString("Timers_EditStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Timer Style.
        /// </summary>
        internal static string Timers_EditTimerStyle {
            get {
                return ResourceManager.GetString("Timers_EditTimerStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Custom Name.
        /// </summary>
        internal static string Timers_EnableCustomName {
            get {
                return ResourceManager.GetString("Timers_EnableCustomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full (D.HH:MM:SS).
        /// </summary>
        internal static string Timers_FullStyle {
            get {
                return ResourceManager.GetString("Timers_FullStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Label.
        /// </summary>
        internal static string Timers_HideLabel {
            get {
                return ResourceManager.GetString("Timers_HideLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Time.
        /// </summary>
        internal static string Timers_HideTime {
            get {
                return ResourceManager.GetString("Timers_HideTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human (e.g. &apos;3 hours&apos;).
        /// </summary>
        internal static string Timers_HumanStyle {
            get {
                return ResourceManager.GetString("Timers_HumanStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timers.
        /// </summary>
        internal static string Timers_Label {
            get {
                return ResourceManager.GetString("Timers_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Seconds (D.HH:MM).
        /// </summary>
        internal static string Timers_NoSecondsStyle {
            get {
                return ResourceManager.GetString("Timers_NoSecondsStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable which timers you would like to see here with &apos;/dd timers&apos; command.
        /// </summary>
        internal static string Timers_NothingEnabled {
            get {
                return ResourceManager.GetString("Timers_NothingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days.
        /// </summary>
        internal static string Timers_NumDays {
            get {
                return ResourceManager.GetString("Timers_NumDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours.
        /// </summary>
        internal static string Timers_NumHours {
            get {
                return ResourceManager.GetString("Timers_NumHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        internal static string Timers_NumMins {
            get {
                return ResourceManager.GetString("Timers_NumMins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds.
        /// </summary>
        internal static string Timers_NumSecs {
            get {
                return ResourceManager.GetString("Timers_NumSecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timers Ordering.
        /// </summary>
        internal static string Timers_Ordering {
            get {
                return ResourceManager.GetString("Timers_Ordering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Timers_Size {
            get {
                return ResourceManager.GetString("Timers_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Options.
        /// </summary>
        internal static string Timers_SizeOptions {
            get {
                return ResourceManager.GetString("Timers_SizeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch to Fit.
        /// </summary>
        internal static string Timers_StretchToFit {
            get {
                return ResourceManager.GetString("Timers_StretchToFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Options.
        /// </summary>
        internal static string Timers_TextOptions {
            get {
                return ResourceManager.GetString("Timers_TextOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Display Options.
        /// </summary>
        internal static string Timers_TimeOptions {
            get {
                return ResourceManager.GetString("Timers_TimeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Tasks Completed.
        /// </summary>
        internal static string Todo_AllCompleted {
            get {
                return ResourceManager.GetString("Todo_AllCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor Corner.
        /// </summary>
        internal static string Todo_AnchorCorner {
            get {
                return ResourceManager.GetString("Todo_AnchorCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Unavailable Tasks.
        /// </summary>
        internal static string Todo_HideUnavailable {
            get {
                return ResourceManager.GetString("Todo_HideUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo.
        /// </summary>
        internal static string Todo_Label {
            get {
                return ResourceManager.GetString("Todo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable a module in Configuration to track Tasks.
        /// </summary>
        internal static string Todo_NothingEnabled {
            get {
                return ResourceManager.GetString("Todo_NothingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Completed Categories.
        /// </summary>
        internal static string Todo_ShowCompleted {
            get {
                return ResourceManager.GetString("Todo_ShowCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Daily Tasks.
        /// </summary>
        internal static string Todo_ShowDailyTasks {
            get {
                return ResourceManager.GetString("Todo_ShowDailyTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Weekly Tasks.
        /// </summary>
        internal static string Todo_ShowWeeklyTasks {
            get {
                return ResourceManager.GetString("Todo_ShowWeeklyTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Display Options.
        /// </summary>
        internal static string Todo_TaskDisplay {
            get {
                return ResourceManager.GetString("Todo_TaskDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Long Label.
        /// </summary>
        internal static string Todo_UseLongLabel {
            get {
                return ResourceManager.GetString("Todo_UseLongLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasure Map.
        /// </summary>
        internal static string TreasureMap_Label {
            get {
                return ResourceManager.GetString("TreasureMap_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Available.
        /// </summary>
        internal static string TreasureMap_MapAvailable {
            get {
                return ResourceManager.GetString("TreasureMap_MapAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Map.
        /// </summary>
        internal static string TreasureMap_NextMap {
            get {
                return ResourceManager.GetString("TreasureMap_NextMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tribal Quests.
        /// </summary>
        internal static string TribalQuests_Label {
            get {
                return ResourceManager.GetString("TribalQuests_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications can be clicked on to teleport to Ul&apos;dah.
        /// </summary>
        internal static string UlDah_ClickableLink {
            get {
                return ResourceManager.GetString("UlDah_ClickableLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A stamp is already available for this instance.
        /// </summary>
        internal static string WondrousTails_AlreadyAvailable {
            get {
                return ResourceManager.GetString("WondrousTails_AlreadyAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Available.
        /// </summary>
        internal static string WondrousTails_BookAvailable {
            get {
                return ResourceManager.GetString("WondrousTails_BookAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can claim a stamp for the last instance.
        /// </summary>
        internal static string WondrousTails_Claimable {
            get {
                return ResourceManager.GetString("WondrousTails_Claimable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications can be clicked on to open wondrous tails book, or to teleport to Idyllshire if you don&apos;t have a book..
        /// </summary>
        internal static string WondrousTails_ClickableLink {
            get {
                return ResourceManager.GetString("WondrousTails_ClickableLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completing this instance will reward you with a stamp.
        /// </summary>
        internal static string WondrousTails_Completable {
            get {
                return ResourceManager.GetString("WondrousTails_Completable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Start/End Notifications.
        /// </summary>
        internal static string WondrousTails_DutyNotifications {
            get {
                return ResourceManager.GetString("WondrousTails_DutyNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wondrous Tails.
        /// </summary>
        internal static string WondrousTails_Label {
            get {
                return ResourceManager.GetString("WondrousTails_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} Re-Rolls Available.
        /// </summary>
        internal static string WondrousTails_RerollCount {
            get {
                return ResourceManager.GetString("WondrousTails_RerollCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This instance is available for a stamp if you re-roll it.
        /// </summary>
        internal static string WondrousTails_RerollNotice {
            get {
                return ResourceManager.GetString("WondrousTails_RerollNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend after leaving duty.
        /// </summary>
        internal static string WondrousTails_ResendNotification {
            get {
                return ResourceManager.GetString("WondrousTails_ResendNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unclaimed Book Warning.
        /// </summary>
        internal static string WondrousTails_UnclaimedBookWarning {
            get {
                return ResourceManager.GetString("WondrousTails_UnclaimedBookWarning", resourceCulture);
            }
        }
    }
}
