//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DailyDuty.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WondrousTailsNode_DutyNotification.
        /// </summary>
        internal static string WondrousTailsNode_DutyNotification {
            get {
                return ResourceManager.GetString("WondrousTailsNode_DutyNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DailyDuty] Time until next daily reset.
        /// </summary>
        internal static string GenericDataNode_NextReset {
            get {
                return ResourceManager.GetString("GenericDataNode_NextReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComparisonMode_Above.
        /// </summary>
        internal static string ComparisonMode_Above {
            get {
                return ResourceManager.GetString("ComparisonMode_Above", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted Not Updated.
        /// </summary>
        internal static string Levequest_AcceptedNotUpdated {
            get {
                return ResourceManager.GetString("Levequest_AcceptedNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Panel.
        /// </summary>
        internal static string TodoOverlay_AddPanel {
            get {
                return ResourceManager.GetString("TodoOverlay_AddPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TodoOverlay_Alignment.
        /// </summary>
        internal static string TodoOverlay_Alignment {
            get {
                return ResourceManager.GetString("TodoOverlay_Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FashionReportMode_AllAttemptsUsed.
        /// </summary>
        internal static string FashionReportMode_AllAttemptsUsed {
            get {
                return ResourceManager.GetString("FashionReportMode_AllAttemptsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliance Raid(s) Incomplete.
        /// </summary>
        internal static string StatusMessages_AllianceRaidIncomplete {
            get {
                return ResourceManager.GetString("StatusMessages_AllianceRaidIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowance Amount.
        /// </summary>
        internal static string CustomDelivery_AllowanceAmount {
            get {
                return ResourceManager.GetString("CustomDelivery_AllowanceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowance Remaining.
        /// </summary>
        internal static string DomanEnclave_AllowanceRemaining {
            get {
                return ResourceManager.GetString("DomanEnclave_AllowanceRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowances Not Updated.
        /// </summary>
        internal static string CustomDelivery_AllowancesNotUpdated {
            get {
                return ResourceManager.GetString("CustomDelivery_AllowancesNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowances Remaining.
        /// </summary>
        internal static string CustomDelivery_AllowancesRemaining {
            get {
                return ResourceManager.GetString("CustomDelivery_AllowancesRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempts Available.
        /// </summary>
        internal static string MiniCactpot_AttemptsAvailable {
            get {
                return ResourceManager.GetString("MiniCactpot_AttemptsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempts Not Updated.
        /// </summary>
        internal static string MiniCactpot_AttemptsNotUpdated {
            get {
                return ResourceManager.GetString("MiniCactpot_AttemptsNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FashionReport_AvailableStatus.
        /// </summary>
        internal static string FashionReport_AvailableStatus {
            get {
                return ResourceManager.GetString("FashionReport_AvailableStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FashionReport_AvailableStatus Not Updated.
        /// </summary>
        internal static string FashionReport_AvailableNotUpdated {
            get {
                return ResourceManager.GetString("FashionReport_AvailableNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FashionReport_AvailableStatus Now.
        /// </summary>
        internal static string GenericDataNode_AvailableNow {
            get {
                return ResourceManager.GetString("GenericDataNode_AvailableNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Alpha.
        /// </summary>
        internal static string TodoOverlay_BackgroundAlpha {
            get {
                return ResourceManager.GetString("TodoOverlay_BackgroundAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComparisonMode_Below.
        /// </summary>
        internal static string ComparisonMode_Below {
            get {
                return ResourceManager.GetString("ComparisonMode_Below", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Expired.
        /// </summary>
        internal static string WondrousTails_BookExpired {
            get {
                return ResourceManager.GetString("WondrousTails_BookExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Obtained.
        /// </summary>
        internal static string WondrousTails_BookObtained {
            get {
                return ResourceManager.GetString("WondrousTails_BookObtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Alpha.
        /// </summary>
        internal static string TodoOverlay_ButtonAlpha {
            get {
                return ResourceManager.GetString("TodoOverlay_ButtonAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge Log.
        /// </summary>
        internal static string ChallengeLog_DisplayName {
            get {
                return ResourceManager.GetString("ChallengeLog_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge Log Duty Finder Warning Selection.
        /// </summary>
        internal static string ChallengeLog_DutyWarningSelection {
            get {
                return ResourceManager.GetString("ChallengeLog_DutyWarningSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge Log(s) Incomplete.
        /// </summary>
        internal static string StatusMessages_ChallengeLogIncomplete {
            get {
                return ResourceManager.GetString("StatusMessages_ChallengeLogIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge Log Tracking Selection.
        /// </summary>
        internal static string ChallengeLog_TrackingSelection {
            get {
                return ResourceManager.GetString("ChallengeLog_TrackingSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge(s) Incomplete.
        /// </summary>
        internal static string StatusMessages_ChallengeIncomplete {
            get {
                return ResourceManager.GetString("StatusMessages_ChallengeIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Channel.
        /// </summary>
        internal static string NotificationSettingsNode_ChatChannel {
            get {
                return ResourceManager.GetString("NotificationSettingsNode_ChatChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Open Configuration.
        /// </summary>
        internal static string ServerInfoBar_ClickOpenConfig {
            get {
                return ResourceManager.GetString("ServerInfoBar_ClickOpenConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Duty Roulette.
        /// </summary>
        internal static string DutyRoulette_ColorRoulette {
            get {
                return ResourceManager.GetString("DutyRoulette_ColorRoulette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompletionStatus_Complete.
        /// </summary>
        internal static string CompletionStatus_Complete {
            get {
                return ResourceManager.GetString("CompletionStatus_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompletionStatus_Complete Color.
        /// </summary>
        internal static string DutyRoulette_CompleteColor {
            get {
                return ResourceManager.GetString("DutyRoulette_CompleteColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Mode.
        /// </summary>
        internal static string FashionReport_CompletionMode {
            get {
                return ResourceManager.GetString("FashionReport_CompletionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleTypes_DailyDutyPlugin_Config.
        /// </summary>
        internal static string DailyDutyPlugin_Config {
            get {
                return ResourceManager.GetString("DailyDutyPlugin_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Completion Count.
        /// </summary>
        internal static string FauxHollows_CompletionCount {
            get {
                return ResourceManager.GetString("FauxHollows_CompletionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Max Allowance.
        /// </summary>
        internal static string DomanEnclave_CurrentMaxAllowance {
            get {
                return ResourceManager.GetString("DomanEnclave_CurrentMaxAllowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Delivery.
        /// </summary>
        internal static string CustomDelivery_DisplayName {
            get {
                return ResourceManager.GetString("CustomDelivery_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Delivery(s) left to reach Threshold.
        /// </summary>
        internal static string StatusMessages_CustomDeliveryIncomplete {
            get {
                return ResourceManager.GetString("StatusMessages_CustomDeliveryIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Reset Message.
        /// </summary>
        internal static string NotificationSettingsNode_CustomReset {
            get {
                return ResourceManager.GetString("NotificationSettingsNode_CustomReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Status Message.
        /// </summary>
        internal static string NotificationSettingsNode_CustomStatus {
            get {
                return ResourceManager.GetString("NotificationSettingsNode_CustomStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleTypes_Daily.
        /// </summary>
        internal static string ModuleTypes_Daily {
            get {
                return ResourceManager.GetString("ModuleTypes_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleTypes_DailyDutyPlugin_Configuration.
        /// </summary>
        internal static string DailyDutyPlugin_Configuration {
            get {
                return ResourceManager.GetString("DailyDutyPlugin_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional_DailyReset.
        /// </summary>
        internal static string Additional_DailyReset {
            get {
                return ResourceManager.GetString("Additional_DailyReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleTypes_Daily Timer.
        /// </summary>
        internal static string ServerInfoBar_DailyTimer {
            get {
                return ResourceManager.GetString("ServerInfoBar_DailyTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleTypes_DailyDuty Button Configuration.
        /// </summary>
        internal static string DutyFinderEnhancements_ButtonConfig {
            get {
                return ResourceManager.GetString("DutyFinderEnhancements_ButtonConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataNodeBase_Data.
        /// </summary>
        internal static string DataNodeBase_Data {
            get {
                return ResourceManager.GetString("DataNodeBase_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional_DataNotSet.
        /// </summary>
        internal static string Additional_DataNotSet {
            get {
                return ResourceManager.GetString("Additional_DataNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WondrousTails_DeadlineLabel.
        /// </summary>
        internal static string WondrousTails_Deadline {
            get {
                return ResourceManager.GetString("WondrousTails_Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleTypes_Debug.
        /// </summary>
        internal static string ModuleTypes_Debug {
            get {
                return ResourceManager.GetString("ModuleTypes_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery(s) Incomplete.
        /// </summary>
        internal static string StatusMessages_DeliveryIncomplete {
            get {
                return ResourceManager.GetString("StatusMessages_DeliveryIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompletionStatus_Disabled.
        /// </summary>
        internal static string CompletionStatus_Disabled {
            get {
                return ResourceManager.GetString("CompletionStatus_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doman Enclave.
        /// </summary>
        internal static string DomanEnclave_DisplayName {
            get {
                return ResourceManager.GetString("DomanEnclave_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donated Not Updated.
        /// </summary>
        internal static string DomanEnclave_DonatedNotUpdated {
            get {
                return ResourceManager.GetString("DomanEnclave_DonatedNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donated This Week.
        /// </summary>
        internal static string DomanEnclave_DonatedThisWeek {
            get {
                return ResourceManager.GetString("DomanEnclave_DonatedThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Finder Enhancements.
        /// </summary>
        internal static string DutyFinderEnhancements_DisplayName {
            get {
                return ResourceManager.GetString("DutyFinderEnhancements_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Finder Integration.
        /// </summary>
        internal static string WondrousTails_DutyFinderIntegration {
            get {
                return ResourceManager.GetString("WondrousTails_DutyFinderIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Roulette.
        /// </summary>
        internal static string DutyRoulette_DisplayName {
            get {
                return ResourceManager.GetString("DutyRoulette_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Duty Finder Warning Entries.
        /// </summary>
        internal static string ChallengeLog_EditDutyEntries {
            get {
                return ResourceManager.GetString("ChallengeLog_EditDutyEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Tracked Challenge Log Entries.
        /// </summary>
        internal static string ChallengeLog_EditTrackedEntries {
            get {
                return ResourceManager.GetString("ChallengeLog_EditTrackedEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Duty Finder Warning.
        /// </summary>
        internal static string ChallengeLog_DutyFinderWarning {
            get {
                return ResourceManager.GetString("ChallengeLog_DutyFinderWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Duty Finder Warning Sound.
        /// </summary>
        internal static string ChallengeLog_DutyFinderWarningSound {
            get {
                return ResourceManager.GetString("ChallengeLog_DutyFinderWarningSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable module to initialize.
        /// </summary>
        internal static string GenericDataNode_EnableModule {
            get {
                return ResourceManager.GetString("GenericDataNode_EnableModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Moving.
        /// </summary>
        internal static string TodoOverlay_EnableMoving {
            get {
                return ResourceManager.GetString("TodoOverlay_EnableMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Moving Timers.
        /// </summary>
        internal static string TimersOverlay_EnableMoving {
            get {
                return ResourceManager.GetString("TimersOverlay_EnableMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventLogging_State.
        /// </summary>
        internal static string EventLogging_Enabled {
            get {
                return ResourceManager.GetString("EventLogging_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Color.
        /// </summary>
        internal static string WondrousTails_EntryColor {
            get {
                return ResourceManager.GetString("WondrousTails_EntryColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventLogging_Status.
        /// </summary>
        internal static string EventLogging_Status {
            get {
                return ResourceManager.GetString("EventLogging_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fashion Report.
        /// </summary>
        internal static string FashionReport_DisplayName {
            get {
                return ResourceManager.GetString("FashionReport_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fashion Report Available.
        /// </summary>
        internal static string FashionReport_Available {
            get {
                return ResourceManager.GetString("FashionReport_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faux Hollows.
        /// </summary>
        internal static string FauxHollows_DisplayName {
            get {
                return ResourceManager.GetString("FauxHollows_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Configuration.
        /// </summary>
        internal static string ServerInfoBar_FeatureConfig {
            get {
                return ResourceManager.GetString("ServerInfoBar_FeatureConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleTypes_Features.
        /// </summary>
        internal static string ModuleTypes_Features {
            get {
                return ResourceManager.GetString("ModuleTypes_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional_GilRemaining.
        /// </summary>
        internal static string Additional_GilRemaining {
            get {
                return ResourceManager.GetString("Additional_GilRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Company Provision.
        /// </summary>
        internal static string GrandCompanyProvision_DisplayName {
            get {
                return ResourceManager.GetString("GrandCompanyProvision_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Company Squadron.
        /// </summary>
        internal static string GrandCompanySquadron_DisplayName {
            get {
                return ResourceManager.GetString("GrandCompanySquadron_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Company Supply.
        /// </summary>
        internal static string GrandCompanySupply_DisplayName {
            get {
                return ResourceManager.GetString("GrandCompanySupply_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Frame.
        /// </summary>
        internal static string TodoOverlay_HideFrame {
            get {
                return ResourceManager.GetString("TodoOverlay_HideFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide in Duties.
        /// </summary>
        internal static string TimersOverlay_HideInDuties {
            get {
                return ResourceManager.GetString("TimersOverlay_HideInDuties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide in Quest Events.
        /// </summary>
        internal static string TimersOverlay_HideInQuests {
            get {
                return ResourceManager.GetString("TimersOverlay_HideInQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Seconds.
        /// </summary>
        internal static string DutyFinderEnhancements_HideSeconds {
            get {
                return ResourceManager.GetString("DutyFinderEnhancements_HideSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Timer Seconds.
        /// </summary>
        internal static string TimersOverlay_HideSeconds {
            get {
                return ResourceManager.GetString("TimersOverlay_HideSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Score.
        /// </summary>
        internal static string FashionReport_HighestScore {
            get {
                return ResourceManager.GetString("FashionReport_HighestScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Score Not Updated.
        /// </summary>
        internal static string FashionReport_ScoreNotUpdated {
            get {
                return ResourceManager.GetString("FashionReport_ScoreNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunt Bill(s) Incomplete.
        /// </summary>
        internal static string StatusMessages_HuntBillIncomplete {
            get {
                return ResourceManager.GetString("StatusMessages_HuntBillIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunt Marks Daily.
        /// </summary>
        internal static string HuntMarksDaily_DisplayName {
            get {
                return ResourceManager.GetString("HuntMarksDaily_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunt Marks Weekly.
        /// </summary>
        internal static string HuntMarksWeekly_DisplayName {
            get {
                return ResourceManager.GetString("HuntMarksWeekly_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TodoPanelNode_Important.
        /// </summary>
        internal static string TodoPanelNode_Important {
            get {
                return ResourceManager.GetString("TodoPanelNode_Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompletionStatus_InProgress.
        /// </summary>
        internal static string CompletionStatus_InProgress {
            get {
                return ResourceManager.GetString("CompletionStatus_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Retelling.
        /// </summary>
        internal static string FauxHollows_IncludeRetelling {
            get {
                return ResourceManager.GetString("FauxHollows_IncludeRetelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompletionStatus_Incomplete.
        /// </summary>
        internal static string CompletionStatus_Incomplete {
            get {
                return ResourceManager.GetString("CompletionStatus_Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompletionStatus_Incomplete Color.
        /// </summary>
        internal static string DutyRoulette_IncompleteColor {
            get {
                return ResourceManager.GetString("DutyRoulette_IncompleteColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Notifications.
        /// </summary>
        internal static string WondrousTails_InstanceNotifications {
            get {
                return ResourceManager.GetString("WondrousTails_InstanceNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumbo Cactpot.
        /// </summary>
        internal static string JumboCactpot_DisplayName {
            get {
                return ResourceManager.GetString("JumboCactpot_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Map Gathered.
        /// </summary>
        internal static string TreasureMap_LastGathered {
            get {
                return ResourceManager.GetString("TreasureMap_LastGathered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Click to Change Mode.
        /// </summary>
        internal static string ServerInfoBar_LeftClickChange {
            get {
                return ResourceManager.GetString("ServerInfoBar_LeftClickChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levequest.
        /// </summary>
        internal static string Levequest_DisplayName {
            get {
                return ResourceManager.GetString("Levequest_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levequest(s) left to reach Threshold.
        /// </summary>
        internal static string StatusMessages_LevequestIncomplete {
            get {
                return ResourceManager.GetString("StatusMessages_LevequestIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levequests Accepted.
        /// </summary>
        internal static string Levequest_Accepted {
            get {
                return ResourceManager.GetString("Levequest_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levequests Available.
        /// </summary>
        internal static string Levequest_Available {
            get {
                return ResourceManager.GetString("Levequest_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Complete When Weekly Tomecapped.
        /// </summary>
        internal static string DutyRoulette_MarkCompleteTomecapped {
            get {
                return ResourceManager.GetString("DutyRoulette_MarkCompleteTomecapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masked Carnivale.
        /// </summary>
        internal static string MaskedCarnivale_DisplayName {
            get {
                return ResourceManager.GetString("MaskedCarnivale_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini Cactpot.
        /// </summary>
        internal static string MiniCactpot_DisplayName {
            get {
                return ResourceManager.GetString("MiniCactpot_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Completed.
        /// </summary>
        internal static string GrandCompanySquadron_MissionCompleted {
            get {
                return ResourceManager.GetString("GrandCompanySquadron_MissionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Completion Time.
        /// </summary>
        internal static string GrandCompanySquadron_CompletionTime {
            get {
                return ResourceManager.GetString("GrandCompanySquadron_CompletionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Not Started.
        /// </summary>
        internal static string StatusMessages_MissionNotStarted {
            get {
                return ResourceManager.GetString("StatusMessages_MissionNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Results Ready.
        /// </summary>
        internal static string StatusMessages_MissionResultsReady {
            get {
                return ResourceManager.GetString("StatusMessages_MissionResultsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Started.
        /// </summary>
        internal static string GrandCompanySquadron_MissionStarted {
            get {
                return ResourceManager.GetString("GrandCompanySquadron_MissionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Time Remaining.
        /// </summary>
        internal static string GrandCompanySquadron_TimeRemaining {
            get {
                return ResourceManager.GetString("GrandCompanySquadron_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataNodeBase_DataNodeBase_ModuleData.
        /// </summary>
        internal static string DataNodeBase_ModuleData {
            get {
                return ResourceManager.GetString("DataNodeBase_ModuleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Failed To Load.
        /// </summary>
        internal static string ModuleOptionNode_FailedToLoad {
            get {
                return ResourceManager.GetString("ModuleOptionNode_FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleTypes_DailyDutyPlugin_ConfigNodeBase_ModuleSettings.
        /// </summary>
        internal static string ConfigNodeBase_ModuleSettings {
            get {
                return ResourceManager.GetString("ConfigNodeBase_ModuleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Status.
        /// </summary>
        internal static string GenericDataNode_ModuleStatus {
            get {
                return ResourceManager.GetString("GenericDataNode_ModuleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Book Available.
        /// </summary>
        internal static string WondrousTails_NewBookAvailable {
            get {
                return ResourceManager.GetString("WondrousTails_NewBookAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleTypes_DailyDutyPlugin_ConfigNodeBase_NoOptions.
        /// </summary>
        internal static string ConfigNodeBase_NoOptions {
            get {
                return ResourceManager.GetString("ConfigNodeBase_NoOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No raids are currently limited..
        /// </summary>
        internal static string Raids_NoneLimited {
            get {
                return ResourceManager.GetString("Raids_NoneLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Raid(s) Incomplete.
        /// </summary>
        internal static string StatusMessages_NormalRaidIncomplete {
            get {
                return ResourceManager.GetString("StatusMessages_NormalRaidIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FashionReport_NotAvailable.
        /// </summary>
        internal static string FashionReport_NotAvailable {
            get {
                return ResourceManager.GetString("FashionReport_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComparisonMode_NotEqual.
        /// </summary>
        internal static string ComparisonMode_NotEqual {
            get {
                return ResourceManager.GetString("ComparisonMode_NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Started.
        /// </summary>
        internal static string GrandCompanySquadron_NotStarted {
            get {
                return ResourceManager.GetString("GrandCompanySquadron_NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Settings.
        /// </summary>
        internal static string NotificationSettingsNode_NotificationSettings {
            get {
                return ResourceManager.GetString("NotificationSettingsNode_NotificationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FashionReportMode_OneAttemptUsed.
        /// </summary>
        internal static string FashionReportMode_OneAttemptUsed {
            get {
                return ResourceManager.GetString("FashionReportMode_OneAttemptUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one panel can be pinned to the quest list at a time..
        /// </summary>
        internal static string TodoOverlay_OnlyOnePinned {
            get {
                return ResourceManager.GetString("TodoOverlay_OnlyOnePinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Configuration.
        /// </summary>
        internal static string ModuleOptionNode_OpenConfig {
            get {
                return ResourceManager.GetString("ModuleOptionNode_OpenConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open DailyDuty.
        /// </summary>
        internal static string DutyFinderEnhancements_OpenDailyDuty {
            get {
                return ResourceManager.GetString("DutyFinderEnhancements_OpenDailyDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleTypes_DailyDutyPlugin_OpenConfigWindow.
        /// </summary>
        internal static string DailyDutyPlugin_OpenConfigWindow {
            get {
                return ResourceManager.GetString("DailyDutyPlugin_OpenConfigWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Main Config.
        /// </summary>
        internal static string TodoOverlay_OpenMainConfig {
            get {
                return ResourceManager.GetString("TodoOverlay_OpenMainConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleTypes_Other.
        /// </summary>
        internal static string ModuleTypes_Other {
            get {
                return ResourceManager.GetString("ModuleTypes_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimerOverlayNode_OverlayTooltip.
        /// </summary>
        internal static string TimerOverlayNode_OverlayTooltip {
            get {
                return ResourceManager.GetString("TimerOverlayNode_OverlayTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Panels.
        /// </summary>
        internal static string TodoOverlay_Panels {
            get {
                return ResourceManager.GetString("TodoOverlay_Panels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel Config.
        /// </summary>
        internal static string PanelConfig_Config {
            get {
                return ResourceManager.GetString("PanelConfig_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin to Quest List.
        /// </summary>
        internal static string TodoOverlay_PinToQuestList {
            get {
                return ResourceManager.GetString("TodoOverlay_PinToQuestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placed Stickers.
        /// </summary>
        internal static string WondrousTails_PlacedStickers {
            get {
                return ResourceManager.GetString("WondrousTails_PlacedStickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an option on the left.
        /// </summary>
        internal static string ModuleBrowserWindow_SelectOption {
            get {
                return ResourceManager.GetString("ModuleBrowserWindow_SelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest Amount.
        /// </summary>
        internal static string TribalQuests_QuestAmount {
            get {
                return ResourceManager.GetString("TribalQuests_QuestAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest(s) left to reach Threshold.
        /// </summary>
        internal static string StatusMessages_QuestIncomplete {
            get {
                return ResourceManager.GetString("StatusMessages_QuestIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raids Alliance.
        /// </summary>
        internal static string RaidsAlliance_DisplayName {
            get {
                return ResourceManager.GetString("RaidsAlliance_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raids Normal.
        /// </summary>
        internal static string RaidsNormal_DisplayName {
            get {
                return ResourceManager.GetString("RaidsNormal_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recolor Duty Finder Entries.
        /// </summary>
        internal static string WondrousTails_RecolorEntries {
            get {
                return ResourceManager.GetString("WondrousTails_RecolorEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Not Updated.
        /// </summary>
        internal static string DomanEnclave_RemainingNotUpdated {
            get {
                return ResourceManager.GetString("DomanEnclave_RemainingNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting.
        /// </summary>
        internal static string StatusMessages_Resetting {
            get {
                return ResourceManager.GetString("StatusMessages_Resetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompletionStatus_ResultsAvailable.
        /// </summary>
        internal static string CompletionStatus_ResultsAvailable {
            get {
                return ResourceManager.GetString("CompletionStatus_ResultsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Click to Open Configuration.
        /// </summary>
        internal static string ServerInfoBar_RightClickOpenConfig {
            get {
                return ResourceManager.GetString("ServerInfoBar_RightClickOpenConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roulette(s) Incomplete.
        /// </summary>
        internal static string StatusMessages_RouletteIncomplete {
            get {
                return ResourceManager.GetString("StatusMessages_RouletteIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimersOverlay_Scale.
        /// </summary>
        internal static string TimersOverlay_Scale {
            get {
                return ResourceManager.GetString("TimersOverlay_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FashionReportMode_ScoredOver80.
        /// </summary>
        internal static string FashionReportMode_ScoredOver80 {
            get {
                return ResourceManager.GetString("FashionReportMode_ScoredOver80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Chance Points.
        /// </summary>
        internal static string WondrousTails_SecondChancePoints {
            get {
                return ResourceManager.GetString("WondrousTails_SecondChancePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send status on login.
        /// </summary>
        internal static string NotificationSettingsNode_LoginStatus {
            get {
                return ResourceManager.GetString("NotificationSettingsNode_LoginStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send status on module reset.
        /// </summary>
        internal static string NotificationSettingsNode_ResetStatus {
            get {
                return ResourceManager.GetString("NotificationSettingsNode_ResetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send status on zone change.
        /// </summary>
        internal static string NotificationSettingsNode_ZoneStatus {
            get {
                return ResourceManager.GetString("NotificationSettingsNode_ZoneStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Info Bar.
        /// </summary>
        internal static string ServerInfoBar_DisplayName {
            get {
                return ResourceManager.GetString("ServerInfoBar_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &quot;Open DailyDuty&quot; Button.
        /// </summary>
        internal static string DutyFinderEnhancements_ShowOpenButton {
            get {
                return ResourceManager.GetString("DutyFinderEnhancements_ShowOpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Clover Indicator.
        /// </summary>
        internal static string WondrousTails_ShowClover {
            get {
                return ResourceManager.GetString("WondrousTails_ShowClover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Countdown Text.
        /// </summary>
        internal static string TimersOverlay_ShowCountdown {
            get {
                return ResourceManager.GetString("TimersOverlay_ShowCountdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Module Label.
        /// </summary>
        internal static string TimersOverlay_ShowLabel {
            get {
                return ResourceManager.GetString("TimersOverlay_ShowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle Available.
        /// </summary>
        internal static string WondrousTails_ShuffleAvailable {
            get {
                return ResourceManager.GetString("WondrousTails_ShuffleAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle Available Notification.
        /// </summary>
        internal static string WondrousTails_ShuffleNotification {
            get {
                return ResourceManager.GetString("WondrousTails_ShuffleNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snooze.
        /// </summary>
        internal static string DataNodeBase_Snooze {
            get {
                return ResourceManager.GetString("DataNodeBase_Snooze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataNodeBase_DataNodeBase_Status.
        /// </summary>
        internal static string DataNodeBase_Status {
            get {
                return ResourceManager.GetString("DataNodeBase_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataNodeBase_DataNodeBase_Status is unavailable, visit the Doman Enclave to update.
        /// </summary>
        internal static string DomanEnclave_UnavailableStatus {
            get {
                return ResourceManager.GetString("DomanEnclave_UnavailableStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataNodeBase_DataNodeBase_Status not Updated.
        /// </summary>
        internal static string DutyRoulette_NotUpdated {
            get {
                return ResourceManager.GetString("DutyRoulette_NotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataNodeBase_DataNodeBase_Status unknown, visit the enclave to update.
        /// </summary>
        internal static string DomanEnclave_UnknownStatus {
            get {
                return ResourceManager.GetString("DomanEnclave_UnknownStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticker Available.
        /// </summary>
        internal static string WondrousTails_StickerAvailable {
            get {
                return ResourceManager.GetString("WondrousTails_StickerAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticker Available Notification.
        /// </summary>
        internal static string WondrousTails_StickerNotification {
            get {
                return ResourceManager.GetString("WondrousTails_StickerNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticker(s) Remaining.
        /// </summary>
        internal static string StatusMessages_StickerRemaining {
            get {
                return ResourceManager.GetString("StatusMessages_StickerRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompletionStatus_Suppressed.
        /// </summary>
        internal static string CompletionStatus_Suppressed {
            get {
                return ResourceManager.GetString("CompletionStatus_Suppressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataNodeBase_DataNodeBase_SnoozeTooltip.
        /// </summary>
        internal static string DataNodeBase_SnoozeTooltip {
            get {
                return ResourceManager.GetString("DataNodeBase_SnoozeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport.
        /// </summary>
        internal static string Teleport_Teleport {
            get {
                return ResourceManager.GetString("Teleport_Teleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport_TeleportingTo.
        /// </summary>
        internal static string Teleport_TeleportingTo {
            get {
                return ResourceManager.GetString("Teleport_TeleportingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Color.
        /// </summary>
        internal static string DutyFinderEnhancements_TextColor {
            get {
                return ResourceManager.GetString("DutyFinderEnhancements_TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Outline Color.
        /// </summary>
        internal static string TodoOverlay_OutlineColor {
            get {
                return ResourceManager.GetString("TodoOverlay_OutlineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JumboCactpot_Ticket.
        /// </summary>
        internal static string JumboCactpot_Ticket {
            get {
                return ResourceManager.GetString("JumboCactpot_Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JumboCactpot_Ticket not Claimed.
        /// </summary>
        internal static string JumboCactpot_TicketNotClaimed {
            get {
                return ResourceManager.GetString("JumboCactpot_TicketNotClaimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JumboCactpot_Ticket Not Updated.
        /// </summary>
        internal static string JumboCactpot_TicketNotUpdated {
            get {
                return ResourceManager.GetString("JumboCactpot_TicketNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JumboCactpot_Ticket(s) Remaining.
        /// </summary>
        internal static string StatusMessages_TicketRemaining {
            get {
                return ResourceManager.GetString("StatusMessages_TicketRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Remaining.
        /// </summary>
        internal static string GenericDataNode_TimeRemaining {
            get {
                return ResourceManager.GetString("GenericDataNode_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Configuration.
        /// </summary>
        internal static string DutyFinderEnhancements_TimerConfig {
            get {
                return ResourceManager.GetString("DutyFinderEnhancements_TimerConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Selection.
        /// </summary>
        internal static string TimersOverlay_Selection {
            get {
                return ResourceManager.GetString("TimersOverlay_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timers Overlay.
        /// </summary>
        internal static string TimersOverlay_DisplayName {
            get {
                return ResourceManager.GetString("TimersOverlay_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo List Overlay.
        /// </summary>
        internal static string TodoListOverlay_DisplayName {
            get {
                return ResourceManager.GetString("TodoListOverlay_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggleable Timer.
        /// </summary>
        internal static string ServerInfoBar_ToggleableTimer {
            get {
                return ResourceManager.GetString("ServerInfoBar_ToggleableTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracked Challenge Log Entries.
        /// </summary>
        internal static string ChallengeLog_TrackedEntries {
            get {
                return ResourceManager.GetString("ChallengeLog_TrackedEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracked Duty Finder Entries.
        /// </summary>
        internal static string DutyRoulette_TrackedEntries {
            get {
                return ResourceManager.GetString("DutyRoulette_TrackedEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracked Duty Finder Warning Entries.
        /// </summary>
        internal static string ChallengeLog_TrackedDutyEntries {
            get {
                return ResourceManager.GetString("ChallengeLog_TrackedDutyEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasure Map.
        /// </summary>
        internal static string TreasureMap_DisplayName {
            get {
                return ResourceManager.GetString("TreasureMap_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasure Map Gatherable.
        /// </summary>
        internal static string TreasureMap_Gatherable {
            get {
                return ResourceManager.GetString("TreasureMap_Gatherable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tribal Quests.
        /// </summary>
        internal static string TribalQuests_DisplayName {
            get {
                return ResourceManager.GetString("TribalQuests_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tribal Quests Available.
        /// </summary>
        internal static string TribalQuests_Available {
            get {
                return ResourceManager.GetString("TribalQuests_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompletionStatus_Unavailable.
        /// </summary>
        internal static string CompletionStatus_Unavailable {
            get {
                return ResourceManager.GetString("CompletionStatus_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unclaimed Book Notification.
        /// </summary>
        internal static string WondrousTails_UnclaimedNotification {
            get {
                return ResourceManager.GetString("WondrousTails_UnclaimedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompletionStatus_Unknown.
        /// </summary>
        internal static string CompletionStatus_Unknown {
            get {
                return ResourceManager.GetString("CompletionStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreal Trial Incomplete.
        /// </summary>
        internal static string StatusMessages_UnrealTrialIncomplete {
            get {
                return ResourceManager.GetString("StatusMessages_UnrealTrialIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsnooze.
        /// </summary>
        internal static string DataNodeBase_Unsnooze {
            get {
                return ResourceManager.GetString("DataNodeBase_Unsnooze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Spacing.
        /// </summary>
        internal static string TodoOverlay_VerticalSpacing {
            get {
                return ResourceManager.GetString("TodoOverlay_VerticalSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait! You forgot your Wondrous Tails book!.
        /// </summary>
        internal static string WondrousTails_ForgotBook {
            get {
                return ResourceManager.GetString("WondrousTails_ForgotBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning Trigger.
        /// </summary>
        internal static string CustomDelivery_WarningTrigger {
            get {
                return ResourceManager.GetString("CustomDelivery_WarningTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleTypes_Weekly.
        /// </summary>
        internal static string ModuleTypes_Weekly {
            get {
                return ResourceManager.GetString("ModuleTypes_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional_WeeklyReset.
        /// </summary>
        internal static string Additional_WeeklyReset {
            get {
                return ResourceManager.GetString("Additional_WeeklyReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleTypes_Weekly Timer.
        /// </summary>
        internal static string ServerInfoBar_WeeklyTimer {
            get {
                return ResourceManager.GetString("ServerInfoBar_WeeklyTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wondrous Tails.
        /// </summary>
        internal static string WondrousTails_DisplayName {
            get {
                return ResourceManager.GetString("WondrousTails_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompletionStatus_Incomplete Task.
        /// </summary>
        internal static string DutyRoulette_IncompleteTask {
            get {
                return ResourceManager.GetString("DutyRoulette_IncompleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompletionStatus_Complete Task.
        /// </summary>
        internal static string DutyRoulette_CompleteTask {
            get {
                return ResourceManager.GetString("DutyRoulette_CompleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Panel.
        /// </summary>
        internal static string TodoOverlay_NewPanel {
            get {
                return ResourceManager.GetString("TodoOverlay_NewPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticker is already available for this duty, be sure to claim it!.
        /// </summary>
        internal static string WondrousTails_StickerAlreadyAvailable {
            get {
                return ResourceManager.GetString("WondrousTails_StickerAlreadyAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completing this duty will reward you with a sticker.
        /// </summary>
        internal static string WondrousTails_CompletingDutyReward {
            get {
                return ResourceManager.GetString("WondrousTails_CompletingDutyReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rerolls Available.
        /// </summary>
        internal static string WondrousTails_RerollsAvailable {
            get {
                return ResourceManager.GetString("WondrousTails_RerollsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stickers Claimable.
        /// </summary>
        internal static string WondrousTails_StickersClaimable {
            get {
                return ResourceManager.GetString("WondrousTails_StickersClaimable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wondrous Tails Duty.
        /// </summary>
        internal static string WondrousTails_Duty {
            get {
                return ResourceManager.GetString("WondrousTails_Duty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompletionStatus_Unknown Status.
        /// </summary>
        internal static string GenericDataNode_UnknownStatus {
            get {
                return ResourceManager.GetString("GenericDataNode_UnknownStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search . . ..
        /// </summary>
        internal static string SearchNode_Placeholder {
            get {
                return ResourceManager.GetString("SearchNode_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DailyDuty] Duty Roulette Feature.
        /// </summary>
        internal static string DutyRoulette_DutyFinderTooltip {
            get {
                return ResourceManager.GetString("DutyRoulette_DutyFinderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DailyDuty] Wondrous Tails Feature.
        /// </summary>
        internal static string WondrousTails_DutyFinderTooltip {
            get {
                return ResourceManager.GetString("WondrousTails_DutyFinderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load, this module has been disabled..
        /// </summary>
        internal static string ModuleManager_LoadFailed {
            get {
                return ResourceManager.GetString("ModuleManager_LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Error: Module failed to load, and errored again while unloading..
        /// </summary>
        internal static string ModuleManager_CriticalError {
            get {
                return ResourceManager.GetString("ModuleManager_CriticalError", resourceCulture);
            }
        }
    }
}
