//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DailyDuty.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DailyDuty] This duty is a Wondrous Tails task.
        /// </summary>
        internal static string _DailyDuty__This_duty_is_a_Wondrous_Tails_task {
            get {
                return ResourceManager.GetString("[DailyDuty] This duty is a Wondrous Tails task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DailyDuty] Time until next daily reset.
        /// </summary>
        internal static string _DailyDuty__Time_until_next_daily_reset {
            get {
                return ResourceManager.GetString("[DailyDuty] Time until next daily reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above.
        /// </summary>
        internal static string Above {
            get {
                return ResourceManager.GetString("Above", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted Not Updated.
        /// </summary>
        internal static string Levequest_AcceptedNotUpdated {
            get {
                return ResourceManager.GetString("Accepted Not Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Panel.
        /// </summary>
        internal static string TodoOverlay_AddPanel {
            get {
                return ResourceManager.GetString("Add Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        internal static string Alignment {
            get {
                return ResourceManager.GetString("Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Attempts Used.
        /// </summary>
        internal static string All_Attempts_Used {
            get {
                return ResourceManager.GetString("All Attempts Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliance Raid(s) Incomplete.
        /// </summary>
        internal static string StatusMessages_AllianceRaidIncomplete {
            get {
                return ResourceManager.GetString("Alliance Raid(s) Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowance Amount.
        /// </summary>
        internal static string CustomDelivery_AllowanceAmount {
            get {
                return ResourceManager.GetString("Allowance Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowance Remaining.
        /// </summary>
        internal static string DomanEnclave_AllowanceRemaining {
            get {
                return ResourceManager.GetString("Allowance Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowances Not Updated.
        /// </summary>
        internal static string CustomDelivery_AllowancesNotUpdated {
            get {
                return ResourceManager.GetString("Allowances Not Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowances Remaining.
        /// </summary>
        internal static string CustomDelivery_AllowancesRemaining {
            get {
                return ResourceManager.GetString("Allowances Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempts Available.
        /// </summary>
        internal static string MiniCactpot_AttemptsAvailable {
            get {
                return ResourceManager.GetString("Attempts Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempts Not Updated.
        /// </summary>
        internal static string MiniCactpot_AttemptsNotUpdated {
            get {
                return ResourceManager.GetString("Attempts Not Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Not Updated.
        /// </summary>
        internal static string FashionReport_AvailableNotUpdated {
            get {
                return ResourceManager.GetString("Available Not Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Now.
        /// </summary>
        internal static string GenericDataNode_AvailableNow {
            get {
                return ResourceManager.GetString("Available Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Alpha.
        /// </summary>
        internal static string TodoOverlay_BackgroundAlpha {
            get {
                return ResourceManager.GetString("Background Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below.
        /// </summary>
        internal static string Below {
            get {
                return ResourceManager.GetString("Below", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Expired.
        /// </summary>
        internal static string WondrousTails_BookExpired {
            get {
                return ResourceManager.GetString("Book Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Obtained.
        /// </summary>
        internal static string WondrousTails_BookObtained {
            get {
                return ResourceManager.GetString("Book Obtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Alpha.
        /// </summary>
        internal static string TodoOverlay_ButtonAlpha {
            get {
                return ResourceManager.GetString("Button Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge Log.
        /// </summary>
        internal static string ChallengeLog_DisplayName {
            get {
                return ResourceManager.GetString("Challenge Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge Log Duty Finder Warning Selection.
        /// </summary>
        internal static string ChallengeLog_DutyWarningSelection {
            get {
                return ResourceManager.GetString("Challenge Log Duty Finder Warning Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge Log(s) Incomplete.
        /// </summary>
        internal static string StatusMessages_ChallengeLogIncomplete {
            get {
                return ResourceManager.GetString("Challenge Log(s) Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge Log Tracking Selection.
        /// </summary>
        internal static string ChallengeLog_TrackingSelection {
            get {
                return ResourceManager.GetString("Challenge Log Tracking Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge(s) Incomplete.
        /// </summary>
        internal static string StatusMessages_ChallengeIncomplete {
            get {
                return ResourceManager.GetString("Challenge(s) Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Channel.
        /// </summary>
        internal static string NotificationSettingsNode_ChatChannel {
            get {
                return ResourceManager.GetString("Chat Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Open Configuration.
        /// </summary>
        internal static string ServerInfoBar_ClickOpenConfig {
            get {
                return ResourceManager.GetString("Click to Open Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Duty Roulette.
        /// </summary>
        internal static string DutyRoulette_ColorRoulette {
            get {
                return ResourceManager.GetString("Color Duty Roulette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Color.
        /// </summary>
        internal static string Complete_Color {
            get {
                return ResourceManager.GetString("Complete Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Mode.
        /// </summary>
        internal static string FashionReport_CompletionMode {
            get {
                return ResourceManager.GetString("Completion Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Completion Count.
        /// </summary>
        internal static string FauxHollows_CompletionCount {
            get {
                return ResourceManager.GetString("Current Completion Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Max Allowance.
        /// </summary>
        internal static string DomanEnclave_CurrentMaxAllowance {
            get {
                return ResourceManager.GetString("Current Max Allowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Delivery.
        /// </summary>
        internal static string CustomDelivery_DisplayName {
            get {
                return ResourceManager.GetString("Custom Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Delivery(s) left to reach Threshold.
        /// </summary>
        internal static string StatusMessages_CustomDeliveryIncomplete {
            get {
                return ResourceManager.GetString("Custom Delivery(s) left to reach Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Reset Message.
        /// </summary>
        internal static string NotificationSettingsNode_CustomReset {
            get {
                return ResourceManager.GetString("Custom Reset Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Status Message.
        /// </summary>
        internal static string NotificationSettingsNode_CustomStatus {
            get {
                return ResourceManager.GetString("Custom Status Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Duty Configuration.
        /// </summary>
        internal static string Daily_Duty_Configuration {
            get {
                return ResourceManager.GetString("Daily Duty Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Reset.
        /// </summary>
        internal static string Additional_DailyReset {
            get {
                return ResourceManager.GetString("Daily Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Timer.
        /// </summary>
        internal static string ServerInfoBar_DailyTimer {
            get {
                return ResourceManager.GetString("Daily Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DailyDuty Button Configuration.
        /// </summary>
        internal static string DutyFinderEnhancements_ButtonConfig {
            get {
                return ResourceManager.GetString("DailyDuty Button Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Not Set.
        /// </summary>
        internal static string Data_Not_Set {
            get {
                return ResourceManager.GetString("Data Not Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        internal static string WondrousTails_Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery(s) Incomplete.
        /// </summary>
        internal static string StatusMessages_DeliveryIncomplete {
            get {
                return ResourceManager.GetString("Delivery(s) Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doman Enclave.
        /// </summary>
        internal static string DomanEnclave_DisplayName {
            get {
                return ResourceManager.GetString("Doman Enclave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donated Not Updated.
        /// </summary>
        internal static string DomanEnclave_DonatedNotUpdated {
            get {
                return ResourceManager.GetString("Donated Not Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donated This Week.
        /// </summary>
        internal static string DomanEnclave_DonatedThisWeek {
            get {
                return ResourceManager.GetString("Donated This Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Finder Enhancements.
        /// </summary>
        internal static string DutyFinderEnhancements_DisplayName {
            get {
                return ResourceManager.GetString("Duty Finder Enhancements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Finder Integration.
        /// </summary>
        internal static string WondrousTails_DutyFinderIntegration {
            get {
                return ResourceManager.GetString("Duty Finder Integration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Roulette.
        /// </summary>
        internal static string DutyRoulette_DisplayName {
            get {
                return ResourceManager.GetString("Duty Roulette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Duty Finder Warning Entries.
        /// </summary>
        internal static string ChallengeLog_EditDutyEntries {
            get {
                return ResourceManager.GetString("Edit Duty Finder Warning Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Tracked Challenge Log Entries.
        /// </summary>
        internal static string ChallengeLog_EditTrackedEntries {
            get {
                return ResourceManager.GetString("Edit Tracked Challenge Log Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Duty Finder Warning.
        /// </summary>
        internal static string ChallengeLog_DutyFinderWarning {
            get {
                return ResourceManager.GetString("Enable Duty Finder Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Duty Finder Warning Sound.
        /// </summary>
        internal static string ChallengeLog_DutyFinderWarningSound {
            get {
                return ResourceManager.GetString("Enable Duty Finder Warning Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable module to initialize.
        /// </summary>
        internal static string GenericDataNode_EnableModule {
            get {
                return ResourceManager.GetString("Enable module to initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Moving.
        /// </summary>
        internal static string TodoOverlay_EnableMoving {
            get {
                return ResourceManager.GetString("Enable Moving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Moving Timers.
        /// </summary>
        internal static string TimersOverlay_EnableMovingTimers {
            get {
                return ResourceManager.GetString("Enable Moving Timers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Color.
        /// </summary>
        internal static string WondrousTails_EntryColor {
            get {
                return ResourceManager.GetString("Entry Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event logging is now.
        /// </summary>
        internal static string Event_logging_is_now {
            get {
                return ResourceManager.GetString("Event logging is now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fashion Report.
        /// </summary>
        internal static string FashionReport_DisplayName {
            get {
                return ResourceManager.GetString("Fashion Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fashion Report Available.
        /// </summary>
        internal static string FashionReport_Available {
            get {
                return ResourceManager.GetString("Fashion Report Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faux Hollows.
        /// </summary>
        internal static string FauxHollows_DisplayName {
            get {
                return ResourceManager.GetString("Faux Hollows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Configuration.
        /// </summary>
        internal static string ServerInfoBar_FeatureConfig {
            get {
                return ResourceManager.GetString("Feature Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        internal static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gil Remaining.
        /// </summary>
        internal static string Additional_GilRemaining {
            get {
                return ResourceManager.GetString("gil Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Company Provision.
        /// </summary>
        internal static string GrandCompanyProvision_DisplayName {
            get {
                return ResourceManager.GetString("Grand Company Provision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Company Squadron.
        /// </summary>
        internal static string GrandCompanySquadron_DisplayName {
            get {
                return ResourceManager.GetString("Grand Company Squadron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Company Supply.
        /// </summary>
        internal static string GrandCompanySupply_DisplayName {
            get {
                return ResourceManager.GetString("Grand Company Supply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Frame.
        /// </summary>
        internal static string TodoOverlay_HideFrame {
            get {
                return ResourceManager.GetString("Hide Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide in Duties.
        /// </summary>
        internal static string TimersOverlay_HideInDuties {
            get {
                return ResourceManager.GetString("Hide in Duties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide in Quest Events.
        /// </summary>
        internal static string TimersOverlay_HideInQuests {
            get {
                return ResourceManager.GetString("Hide in Quest Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Seconds.
        /// </summary>
        internal static string DutyFinderEnhancements_HideSeconds {
            get {
                return ResourceManager.GetString("Hide Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Timer Seconds.
        /// </summary>
        internal static string TimersOverlay_HideSeconds {
            get {
                return ResourceManager.GetString("Hide Timer Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Score.
        /// </summary>
        internal static string FashionReport_HighestScore {
            get {
                return ResourceManager.GetString("Highest Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Score Not Updated.
        /// </summary>
        internal static string FashionReport_ScoreNotUpdated {
            get {
                return ResourceManager.GetString("Highest Score Not Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunt Bill(s) Incomplete.
        /// </summary>
        internal static string StatusMessages_HuntBillIncomplete {
            get {
                return ResourceManager.GetString("Hunt Bill(s) Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunt Marks Daily.
        /// </summary>
        internal static string HuntMarksDaily_DisplayName {
            get {
                return ResourceManager.GetString("Hunt Marks Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunt Marks Weekly.
        /// </summary>
        internal static string HuntMarksWeekly_DisplayName {
            get {
                return ResourceManager.GetString("Hunt Marks Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important.
        /// </summary>
        internal static string Important {
            get {
                return ResourceManager.GetString("Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string In_Progress {
            get {
                return ResourceManager.GetString("In Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Retelling.
        /// </summary>
        internal static string FauxHollows_IncludeRetelling {
            get {
                return ResourceManager.GetString("Include Retelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete.
        /// </summary>
        internal static string Incomplete {
            get {
                return ResourceManager.GetString("Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Color.
        /// </summary>
        internal static string Incomplete_Color {
            get {
                return ResourceManager.GetString("Incomplete Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Notifications.
        /// </summary>
        internal static string WondrousTails_InstanceNotifications {
            get {
                return ResourceManager.GetString("Instance Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumbo Cactpot.
        /// </summary>
        internal static string JumboCactpot_DisplayName {
            get {
                return ResourceManager.GetString("Jumbo Cactpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Map Gathered.
        /// </summary>
        internal static string TreasureMap_LastGathered {
            get {
                return ResourceManager.GetString("Last Map Gathered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Click to Change Mode.
        /// </summary>
        internal static string ServerInfoBar_LeftClickChange {
            get {
                return ResourceManager.GetString("Left Click to Change Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levequest.
        /// </summary>
        internal static string Levequest {
            get {
                return ResourceManager.GetString("Levequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levequest(s) left to reach Threshold.
        /// </summary>
        internal static string StatusMessages_LevequestIncomplete {
            get {
                return ResourceManager.GetString("Levequest(s) left to reach Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levequests Accepted.
        /// </summary>
        internal static string Levequest_Accepted {
            get {
                return ResourceManager.GetString("Levequests Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levequests Available.
        /// </summary>
        internal static string Levequest_Available {
            get {
                return ResourceManager.GetString("Levequests Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Complete When Weekly Tomecapped.
        /// </summary>
        internal static string DutyRoulette_MarkCompleteTomecapped {
            get {
                return ResourceManager.GetString("Mark Complete When Weekly Tomecapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masked Carnivale.
        /// </summary>
        internal static string MaskedCarnivale_DisplayName {
            get {
                return ResourceManager.GetString("Masked Carnivale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini Cactpot.
        /// </summary>
        internal static string MiniCactpot_DisplayName {
            get {
                return ResourceManager.GetString("Mini Cactpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Completed.
        /// </summary>
        internal static string GrandCompanySquadron_MissionCompleted {
            get {
                return ResourceManager.GetString("Mission Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Completion Time.
        /// </summary>
        internal static string GrandCompanySquadron_CompletionTime {
            get {
                return ResourceManager.GetString("Mission Completion Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Not Started.
        /// </summary>
        internal static string StatusMessages_MissionNotStarted {
            get {
                return ResourceManager.GetString("Mission Not Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Results Ready.
        /// </summary>
        internal static string StatusMessages_MissionResultsReady {
            get {
                return ResourceManager.GetString("Mission Results Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Started.
        /// </summary>
        internal static string GrandCompanySquadron_MissionStarted {
            get {
                return ResourceManager.GetString("Mission Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Time Remaining.
        /// </summary>
        internal static string GrandCompanySquadron_TimeRemaining {
            get {
                return ResourceManager.GetString("Mission Time Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Data.
        /// </summary>
        internal static string Module_Data {
            get {
                return ResourceManager.GetString("Module Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Failed To Load.
        /// </summary>
        internal static string ModuleOptionNode_FailedToLoad {
            get {
                return ResourceManager.GetString("Module Failed To Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Settings.
        /// </summary>
        internal static string Module_Settings {
            get {
                return ResourceManager.GetString("Module Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Status.
        /// </summary>
        internal static string GenericDataNode_ModuleStatus {
            get {
                return ResourceManager.GetString("Module Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Book Available.
        /// </summary>
        internal static string WondrousTails_NewBookAvailable {
            get {
                return ResourceManager.GetString("New Book Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Reset.
        /// </summary>
        internal static string GenericDataNode_NextReset {
            get {
                return ResourceManager.GetString("Next Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No options available for this module.
        /// </summary>
        internal static string No_options_available_for_this_module {
            get {
                return ResourceManager.GetString("No options available for this module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No raids are currently limited..
        /// </summary>
        internal static string Raids_NoneLimited {
            get {
                return ResourceManager.GetString("No raids are currently limited.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Raid(s) Incomplete.
        /// </summary>
        internal static string StatusMessages_NormalRaidIncomplete {
            get {
                return ResourceManager.GetString("Normal Raid(s) Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        internal static string Not_Available {
            get {
                return ResourceManager.GetString("Not Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Equal.
        /// </summary>
        internal static string Not_Equal {
            get {
                return ResourceManager.GetString("Not Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Started.
        /// </summary>
        internal static string GrandCompanySquadron_NotStarted {
            get {
                return ResourceManager.GetString("Not Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Settings.
        /// </summary>
        internal static string NotificationSettingsNode_NotificationSettings {
            get {
                return ResourceManager.GetString("Notification Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Attempt Used.
        /// </summary>
        internal static string One_Attempt_Used {
            get {
                return ResourceManager.GetString("One Attempt Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one panel can be pinned to the quest list at a time..
        /// </summary>
        internal static string TodoOverlay_OnlyOnePinned {
            get {
                return ResourceManager.GetString("Only one panel can be pinned to the quest list at a time.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Configuration.
        /// </summary>
        internal static string ModuleOptionNode_OpenConfig {
            get {
                return ResourceManager.GetString("Open Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open DailyDuty.
        /// </summary>
        internal static string DutyFinderEnhancements_OpenDailyDuty {
            get {
                return ResourceManager.GetString("Open DailyDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open DailyDuty Config Window.
        /// </summary>
        internal static string Open_DailyDuty_Config_Window {
            get {
                return ResourceManager.GetString("Open DailyDuty Config Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Main Config.
        /// </summary>
        internal static string TodoOverlay_OpenMainConfig {
            get {
                return ResourceManager.GetString("Open Main Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay from DailyDuty plugin.
        /// </summary>
        internal static string Overlay_from_DailyDuty_plugin {
            get {
                return ResourceManager.GetString("Overlay from DailyDuty plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Panels.
        /// </summary>
        internal static string TodoOverlay_Panels {
            get {
                return ResourceManager.GetString("Overlay Panels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel Config.
        /// </summary>
        internal static string PanelConfig_Config {
            get {
                return ResourceManager.GetString("Panel Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin to Quest List.
        /// </summary>
        internal static string TodoOverlay_PinToQuestList {
            get {
                return ResourceManager.GetString("Pin to Quest List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placed Stickers.
        /// </summary>
        internal static string WondrousTails_PlacedStickers {
            get {
                return ResourceManager.GetString("Placed Stickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an option on the left.
        /// </summary>
        internal static string ModuleBrowserWindow_SelectOption {
            get {
                return ResourceManager.GetString("Please select an option on the left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest Amount.
        /// </summary>
        internal static string TribalQuests_QuestAmount {
            get {
                return ResourceManager.GetString("Quest Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest(s) left to reach Threshold.
        /// </summary>
        internal static string StatusMessages_QuestIncomplete {
            get {
                return ResourceManager.GetString("Quest(s) left to reach Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raids Alliance.
        /// </summary>
        internal static string RaidsAlliance_DisplayName {
            get {
                return ResourceManager.GetString("Raids Alliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raids Normal.
        /// </summary>
        internal static string RaidsNormal_DisplayName {
            get {
                return ResourceManager.GetString("Raids Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recolor Duty Finder Entries.
        /// </summary>
        internal static string WondrousTails_RecolorEntries {
            get {
                return ResourceManager.GetString("Recolor Duty Finder Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Not Updated.
        /// </summary>
        internal static string DomanEnclave_RemainingNotUpdated {
            get {
                return ResourceManager.GetString("Remaining Not Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting.
        /// </summary>
        internal static string StatusMessages_Resetting {
            get {
                return ResourceManager.GetString("Resetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results Available.
        /// </summary>
        internal static string Results_Available {
            get {
                return ResourceManager.GetString("Results Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Click to Open Configuration.
        /// </summary>
        internal static string ServerInfoBar_RightClickOpenConfig {
            get {
                return ResourceManager.GetString("Right Click to Open Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roulette(s) Incomplete.
        /// </summary>
        internal static string StatusMessages_RouletteIncomplete {
            get {
                return ResourceManager.GetString("Roulette(s) Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scored Over 80.
        /// </summary>
        internal static string Scored_Over_80 {
            get {
                return ResourceManager.GetString("Scored Over 80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Chance Points.
        /// </summary>
        internal static string WondrousTails_SecondChancePoints {
            get {
                return ResourceManager.GetString("Second Chance Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send status on login.
        /// </summary>
        internal static string NotificationSettingsNode_LoginStatus {
            get {
                return ResourceManager.GetString("Send status on login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send status on module reset.
        /// </summary>
        internal static string NotificationSettingsNode_ResetStatus {
            get {
                return ResourceManager.GetString("Send status on module reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send status on zone change.
        /// </summary>
        internal static string NotificationSettingsNode_ZoneStatus {
            get {
                return ResourceManager.GetString("Send status on zone change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Info Bar.
        /// </summary>
        internal static string ServerInfoBar_DisplayName {
            get {
                return ResourceManager.GetString("Server Info Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &quot;Open DailyDuty&quot; Button.
        /// </summary>
        internal static string DutyFinderEnhancements_ShowOpenButton {
            get {
                return ResourceManager.GetString("Show \"Open DailyDuty\" Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Clover Indicator.
        /// </summary>
        internal static string WondrousTails_ShowClover {
            get {
                return ResourceManager.GetString("Show Clover Indicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Countdown Text.
        /// </summary>
        internal static string TimersOverlay_ShowCountdown {
            get {
                return ResourceManager.GetString("Show Countdown Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Module Label.
        /// </summary>
        internal static string TimersOverlay_ShowLabel {
            get {
                return ResourceManager.GetString("Show Module Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle Available.
        /// </summary>
        internal static string WondrousTails_ShuffleAvailable {
            get {
                return ResourceManager.GetString("Shuffle Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle Available Notification.
        /// </summary>
        internal static string WondrousTails_ShuffleNotification {
            get {
                return ResourceManager.GetString("Shuffle Available Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snooze.
        /// </summary>
        internal static string Snooze {
            get {
                return ResourceManager.GetString("Snooze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is unavailable, visit the Doman Enclave to update.
        /// </summary>
        internal static string DomanEnclave_UnavailableStatus {
            get {
                return ResourceManager.GetString("Status is unavailable, visit the Doman Enclave to update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status not Updated.
        /// </summary>
        internal static string DutyRoulette_NotUpdated {
            get {
                return ResourceManager.GetString("Status not Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status unknown, visit the enclave to update.
        /// </summary>
        internal static string DomanEnclave_UnknownStatus {
            get {
                return ResourceManager.GetString("Status unknown, visit the enclave to update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticker Available.
        /// </summary>
        internal static string WondrousTails_StickerAvailable {
            get {
                return ResourceManager.GetString("Sticker Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticker Available Notification.
        /// </summary>
        internal static string WondrousTails_StickerNotification {
            get {
                return ResourceManager.GetString("Sticker Available Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticker(s) Remaining.
        /// </summary>
        internal static string StatusMessages_StickerRemaining {
            get {
                return ResourceManager.GetString("Sticker(s) Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppressed.
        /// </summary>
        internal static string Suppressed {
            get {
                return ResourceManager.GetString("Suppressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppresses notification until the next reset.
        /// </summary>
        internal static string Suppresses_notification_until_the_next_reset {
            get {
                return ResourceManager.GetString("Suppresses notification until the next reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport.
        /// </summary>
        internal static string Teleport {
            get {
                return ResourceManager.GetString("Teleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleporting to.
        /// </summary>
        internal static string Teleporting_to {
            get {
                return ResourceManager.GetString("Teleporting to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Color.
        /// </summary>
        internal static string DutyFinderEnhancements_TextColor {
            get {
                return ResourceManager.GetString("Text Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Outline Color.
        /// </summary>
        internal static string TodoOverlay_OutlineColor {
            get {
                return ResourceManager.GetString("Text Outline Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket.
        /// </summary>
        internal static string Ticket {
            get {
                return ResourceManager.GetString("Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket not Claimed.
        /// </summary>
        internal static string JumboCactpot_TicketNotClaimed {
            get {
                return ResourceManager.GetString("Ticket not Claimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Not Updated.
        /// </summary>
        internal static string JumboCactpot_TicketNotUpdated {
            get {
                return ResourceManager.GetString("Ticket Not Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket(s) Remaining.
        /// </summary>
        internal static string StatusMessages_TicketRemaining {
            get {
                return ResourceManager.GetString("Ticket(s) Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Remaining.
        /// </summary>
        internal static string GenericDataNode_TimeRemaining {
            get {
                return ResourceManager.GetString("Time Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Configuration.
        /// </summary>
        internal static string DutyFinderEnhancements_TimerConfig {
            get {
                return ResourceManager.GetString("Timer Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Selection.
        /// </summary>
        internal static string TimersOverlay_Selection {
            get {
                return ResourceManager.GetString("Timer Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timers Overlay.
        /// </summary>
        internal static string TimersOverlay_DisplayName {
            get {
                return ResourceManager.GetString("Timers Overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo List Overlay.
        /// </summary>
        internal static string TodoListOverlay_DisplayName {
            get {
                return ResourceManager.GetString("Todo List Overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggleable Timer.
        /// </summary>
        internal static string ServerInfoBar_ToggleableTimer {
            get {
                return ResourceManager.GetString("Toggleable Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracked Challenge Log Entries.
        /// </summary>
        internal static string ChallengeLog_TrackedEntries {
            get {
                return ResourceManager.GetString("Tracked Challenge Log Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracked Duty Finder Entries.
        /// </summary>
        internal static string DutyRoulette_TrackedEntries {
            get {
                return ResourceManager.GetString("Tracked Duty Finder Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracked Duty Finder Warning Entries.
        /// </summary>
        internal static string ChallengeLog_TrackedDutyEntries {
            get {
                return ResourceManager.GetString("Tracked Duty Finder Warning Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasure Map.
        /// </summary>
        internal static string TreasureMap_DisplayName {
            get {
                return ResourceManager.GetString("Treasure Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasure Map Gatherable.
        /// </summary>
        internal static string TreasureMap_Gatherable {
            get {
                return ResourceManager.GetString("Treasure Map Gatherable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tribal Quests.
        /// </summary>
        internal static string TribalQuests_DisplayName {
            get {
                return ResourceManager.GetString("Tribal Quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tribal Quests Available.
        /// </summary>
        internal static string TribalQuests_Available {
            get {
                return ResourceManager.GetString("Tribal Quests Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        internal static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unclaimed Book Notification.
        /// </summary>
        internal static string WondrousTails_UnclaimedNotification {
            get {
                return ResourceManager.GetString("Unclaimed Book Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreal Trial Incomplete.
        /// </summary>
        internal static string StatusMessages_UnrealTrialIncomplete {
            get {
                return ResourceManager.GetString("Unreal Trial Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsnooze.
        /// </summary>
        internal static string Unsnooze {
            get {
                return ResourceManager.GetString("Unsnooze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Spacing.
        /// </summary>
        internal static string TodoOverlay_VerticalSpacing {
            get {
                return ResourceManager.GetString("Vertical Spacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait! You forgot your Wondrous Tails book!.
        /// </summary>
        internal static string Wait__You_forgot_your_Wondrous_Tails_book_ {
            get {
                return ResourceManager.GetString("Wait! You forgot your Wondrous Tails book!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning Trigger.
        /// </summary>
        internal static string CustomDelivery_WarningTrigger {
            get {
                return ResourceManager.GetString("Warning Trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Reset.
        /// </summary>
        internal static string Additional_WeeklyReset {
            get {
                return ResourceManager.GetString("Weekly Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Timer.
        /// </summary>
        internal static string ServerInfoBar_WeeklyTimer {
            get {
                return ResourceManager.GetString("Weekly Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wondrous Tails.
        /// </summary>
        internal static string WondrousTails_DisplayName {
            get {
                return ResourceManager.GetString("Wondrous Tails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Task.
        /// </summary>
        internal static string DutyRoulette_IncompleteTask {
            get {
                return ResourceManager.GetString("Incomplete Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Task.
        /// </summary>
        internal static string DutyRoulette_CompleteTask {
            get {
                return ResourceManager.GetString("Complete Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Panel.
        /// </summary>
        internal static string TodoOverlay_NewPanel {
            get {
                return ResourceManager.GetString("New Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticker is already available for this duty, be sure to claim it!.
        /// </summary>
        internal static string WondrousTails_StickerAlreadyAvailable {
            get {
                return ResourceManager.GetString("Sticker is already available for this duty, be sure to claim it!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completing this duty will reward you with a sticker.
        /// </summary>
        internal static string WondrousTails_CompletingDutyReward {
            get {
                return ResourceManager.GetString("Completing this duty will reward you with a sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rerolls Available.
        /// </summary>
        internal static string WondrousTails_RerollsAvailable {
            get {
                return ResourceManager.GetString("Rerolls Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stickers Claimable.
        /// </summary>
        internal static string WondrousTails_StickersClaimable {
            get {
                return ResourceManager.GetString("Stickers Claimable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wondrous Tails Duty.
        /// </summary>
        internal static string WondrousTails_Duty {
            get {
                return ResourceManager.GetString("Wondrous Tails Duty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Status.
        /// </summary>
        internal static string Unknown_Status {
            get {
                return ResourceManager.GetString("Unknown Status", resourceCulture);
            }
        }
    }
}
