//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyDuty.System.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DailyDuty.System.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted Levequests.
        /// </summary>
        internal static string AcceptedLevequests {
            get {
                return ResourceManager.GetString("AcceptedLevequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Allowances Used.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowances Available.
        /// </summary>
        internal static string AllowancesAvailable {
            get {
                return ResourceManager.GetString("AllowancesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowances Remaining.
        /// </summary>
        internal static string AllowancesRemaining {
            get {
                return ResourceManager.GetString("AllowancesRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Limit Reached.
        /// </summary>
        internal static string AtWeeklyTomestoneLimit {
            get {
                return ResourceManager.GetString("AtWeeklyTomestoneLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting User Action.
        /// </summary>
        internal static string AwaitingUserAction {
            get {
                return ResourceManager.GetString("AwaitingUserAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Expired.
        /// </summary>
        internal static string BookExpired {
            get {
                return ResourceManager.GetString("BookExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget Remaining.
        /// </summary>
        internal static string BudgetRemaining {
            get {
                return ResourceManager.GetString("BudgetRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot teleport in this situation.
        /// </summary>
        internal static string CannotTeleportNow {
            get {
                return ResourceManager.GetString("CannotTeleportNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casting Teleport.
        /// </summary>
        internal static string CastingTeleport {
            get {
                return ResourceManager.GetString("CastingTeleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge Log.
        /// </summary>
        internal static string ChallengeLog {
            get {
                return ResourceManager.GetString("ChallengeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenges Remaining.
        /// </summary>
        internal static string ChallengesRemaining {
            get {
                return ResourceManager.GetString("ChallengesRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claimed Tickets.
        /// </summary>
        internal static string ClaimedTickets {
            get {
                return ResourceManager.GetString("ClaimedTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clickable Link.
        /// </summary>
        internal static string ClickableLink {
            get {
                return ResourceManager.GetString("ClickableLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module is considered &apos;Complete&apos; when the condition is met.
        /// </summary>
        internal static string ComparisonHelp {
            get {
                return ResourceManager.GetString("ComparisonHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison Mode.
        /// </summary>
        internal static string ComparisonMode {
            get {
                return ResourceManager.GetString("ComparisonMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete When Tomecapped.
        /// </summary>
        internal static string CompleteWhenTomeCapped {
            get {
                return ResourceManager.GetString("CompleteWhenTomeCapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks task as complete when you are at the tomestone weekly limit.
        /// </summary>
        internal static string CompleteWhenTomeCappedHelp {
            get {
                return ResourceManager.GetString("CompleteWhenTomeCappedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completing this instance will reward you with a stamp.
        /// </summary>
        internal static string CompletionAvailable {
            get {
                return ResourceManager.GetString("CompletionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Mode.
        /// </summary>
        internal static string CompletionMode {
            get {
                return ResourceManager.GetString("CompletionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Color.
        /// </summary>
        internal static string CurrentColor {
            get {
                return ResourceManager.GetString("CurrentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Drop Count.
        /// </summary>
        internal static string CurrentNumDrops {
            get {
                return ResourceManager.GetString("CurrentNumDrops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Status.
        /// </summary>
        internal static string CurrentStatus {
            get {
                return ResourceManager.GetString("CurrentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Weekly Tomestones.
        /// </summary>
        internal static string CurrentWeeklyTomestones {
            get {
                return ResourceManager.GetString("CurrentWeeklyTomestones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Delivery.
        /// </summary>
        internal static string CustomDelivery {
            get {
                return ResourceManager.GetString("CustomDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Tasks Label.
        /// </summary>
        internal static string DailyTasksLabel {
            get {
                return ResourceManager.GetString("DailyTasksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        internal static string Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance to Khloe.
        /// </summary>
        internal static string DistanceToKhloe {
            get {
                return ResourceManager.GetString("DistanceToKhloe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doman Enclave.
        /// </summary>
        internal static string DomanEnclave {
            get {
                return ResourceManager.GetString("DomanEnclave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications can be clicked on to teleport to the Doman Enclave.
        /// </summary>
        internal static string DomanEnclaveTeleport {
            get {
                return ResourceManager.GetString("DomanEnclaveTeleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donated.
        /// </summary>
        internal static string DonatedThisWeek {
            get {
                return ResourceManager.GetString("DonatedThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Name.
        /// </summary>
        internal static string DutyName {
            get {
                return ResourceManager.GetString("DutyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Roulette.
        /// </summary>
        internal static string DutyRoulette {
            get {
                return ResourceManager.GetString("DutyRoulette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications can be clicked on to open the Duty Finder.
        /// </summary>
        internal static string DutyRouletteOpenDutyFinder {
            get {
                return ResourceManager.GetString("DutyRouletteOpenDutyFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Custom Channel.
        /// </summary>
        internal static string EnableCustomChannel {
            get {
                return ResourceManager.GetString("EnableCustomChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Custom Reset Message.
        /// </summary>
        internal static string EnableCustomResetMessage {
            get {
                return ResourceManager.GetString("EnableCustomResetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Custom Status Message.
        /// </summary>
        internal static string EnableCustomStatusMessage {
            get {
                return ResourceManager.GetString("EnableCustomStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Daily.
        /// </summary>
        internal static string EnableDailyTasks {
            get {
                return ResourceManager.GetString("EnableDailyTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Special.
        /// </summary>
        internal static string EnableSpecialTasks {
            get {
                return ResourceManager.GetString("EnableSpecialTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Weekly.
        /// </summary>
        internal static string EnableWeeklyTasks {
            get {
                return ResourceManager.GetString("EnableWeeklyTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal To.
        /// </summary>
        internal static string EqualTo {
            get {
                return ResourceManager.GetString("EqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fashion Report.
        /// </summary>
        internal static string FashionReport {
            get {
                return ResourceManager.GetString("FashionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fashion Report Available.
        /// </summary>
        internal static string FashionReportAvailable {
            get {
                return ResourceManager.GetString("FashionReportAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faux Hollows.
        /// </summary>
        internal static string FauxHollows {
            get {
                return ResourceManager.GetString("FauxHollows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faux Hollows Completions.
        /// </summary>
        internal static string FauxHollowsCompletions {
            get {
                return ResourceManager.GetString("FauxHollowsCompletions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait! You forgot your book!.
        /// </summary>
        internal static string ForgotBookWarning {
            get {
                return ResourceManager.GetString("ForgotBookWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gil Remaining.
        /// </summary>
        internal static string GilRemaining {
            get {
                return ResourceManager.GetString("GilRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications can be clicked on to teleport to the Gold Saucer.
        /// </summary>
        internal static string GoldSaucerTeleport {
            get {
                return ResourceManager.GetString("GoldSaucerTeleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Company (Provision).
        /// </summary>
        internal static string GrandCompanyProvision {
            get {
                return ResourceManager.GetString("GrandCompanyProvision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Company (Squadron).
        /// </summary>
        internal static string GrandCompanySquadron {
            get {
                return ResourceManager.GetString("GrandCompanySquadron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Company (Supply).
        /// </summary>
        internal static string GrandCompanySupply {
            get {
                return ResourceManager.GetString("GrandCompanySupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Outline Color.
        /// </summary>
        internal static string HeaderOutlineColor {
            get {
                return ResourceManager.GetString("HeaderOutlineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Disabled.
        /// </summary>
        internal static string HideDisabled {
            get {
                return ResourceManager.GetString("HideDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide During Duties.
        /// </summary>
        internal static string HideInDuties {
            get {
                return ResourceManager.GetString("HideInDuties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide During Quest Events.
        /// </summary>
        internal static string HideInQuestEvent {
            get {
                return ResourceManager.GetString("HideInQuestEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Score.
        /// </summary>
        internal static string HighestScore {
            get {
                return ResourceManager.GetString("HighestScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Score.
        /// </summary>
        internal static string HighestWeeklyScore {
            get {
                return ResourceManager.GetString("HighestWeeklyScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunt Marks (Daily).
        /// </summary>
        internal static string HuntMarksDaily {
            get {
                return ResourceManager.GetString("HuntMarksDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunt Marks (Weekly).
        /// </summary>
        internal static string HuntMarksWeekly {
            get {
                return ResourceManager.GetString("HuntMarksWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunts Remaining.
        /// </summary>
        internal static string HuntsRemaining {
            get {
                return ResourceManager.GetString("HuntsRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications can be clicked on to teleport to Idyllshire.
        /// </summary>
        internal static string IdyllshireTeleport {
            get {
                return ResourceManager.GetString("IdyllshireTeleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Retelling.
        /// </summary>
        internal static string IncludeRetelling {
            get {
                return ResourceManager.GetString("IncludeRetelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete.
        /// </summary>
        internal static string Incomplete {
            get {
                return ResourceManager.GetString("Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use the teleport function, you must install the &quot;Teleporter&quot; plugin.
        /// </summary>
        internal static string InstallTeleporterError {
            get {
                return ResourceManager.GetString("InstallTeleporterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Notifications.
        /// </summary>
        internal static string InstanceNotifications {
            get {
                return ResourceManager.GetString("InstanceNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When entering a duty, display if the duty needs to be rerolled, or is already available.
        /// </summary>
        internal static string InstanceNotificationsHelp {
            get {
                return ResourceManager.GetString("InstanceNotificationsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumbo Cactpot.
        /// </summary>
        internal static string JumboCactpot {
            get {
                return ResourceManager.GetString("JumboCactpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Map Gathered.
        /// </summary>
        internal static string LastMapGathered {
            get {
                return ResourceManager.GetString("LastMapGathered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Than.
        /// </summary>
        internal static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Than or Equal.
        /// </summary>
        internal static string LessThanOrEqual {
            get {
                return ResourceManager.GetString("LessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levequest.
        /// </summary>
        internal static string Levequest {
            get {
                return ResourceManager.GetString("Levequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levequest Allowances.
        /// </summary>
        internal static string LevequestAllowances {
            get {
                return ResourceManager.GetString("LevequestAllowances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Spacing.
        /// </summary>
        internal static string LineSpacing {
            get {
                return ResourceManager.GetString("LineSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Notification Message on Login.
        /// </summary>
        internal static string LoginMessage {
            get {
                return ResourceManager.GetString("LoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Available.
        /// </summary>
        internal static string MapAvailable {
            get {
                return ResourceManager.GetString("MapAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masked Carnivale.
        /// </summary>
        internal static string MaskedCarnivale {
            get {
                return ResourceManager.GetString("MaskedCarnivale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini Cactpot.
        /// </summary>
        internal static string MiniCactpot {
            get {
                return ResourceManager.GetString("MiniCactpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Available.
        /// </summary>
        internal static string MissionAvailable {
            get {
                return ResourceManager.GetString("MissionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Completed.
        /// </summary>
        internal static string MissionCompleted {
            get {
                return ResourceManager.GetString("MissionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Complete Time.
        /// </summary>
        internal static string MissionCompleteTime {
            get {
                return ResourceManager.GetString("MissionCompleteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Started.
        /// </summary>
        internal static string MissionStarted {
            get {
                return ResourceManager.GetString("MissionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Configuration.
        /// </summary>
        internal static string ModuleConfiguration {
            get {
                return ResourceManager.GetString("ModuleConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Data.
        /// </summary>
        internal static string ModuleData {
            get {
                return ResourceManager.GetString("ModuleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Data.
        /// </summary>
        internal static string ModuleDataTab_TabName_Module_Data {
            get {
                return ResourceManager.GetString("ModuleDataTab_TabName_Module_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Enable.
        /// </summary>
        internal static string ModuleEnable {
            get {
                return ResourceManager.GetString("ModuleEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Reset.
        /// </summary>
        internal static string ModuleReset {
            get {
                return ResourceManager.GetString("ModuleReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleStatus.
        /// </summary>
        internal static string ModuleStatus {
            get {
                return ResourceManager.GetString("ModuleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Suppression.
        /// </summary>
        internal static string ModuleSuppression {
            get {
                return ResourceManager.GetString("ModuleSuppression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silence notifications until the next module reset.
        /// </summary>
        internal static string ModuleSuppressionHelp {
            get {
                return ResourceManager.GetString("ModuleSuppressionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near Khloe.
        /// </summary>
        internal static string NearKhloe {
            get {
                return ResourceManager.GetString("NearKhloe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Book Available.
        /// </summary>
        internal static string NewBookAvailable {
            get {
                return ResourceManager.GetString("NewBookAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Reset.
        /// </summary>
        internal static string NextReset {
            get {
                return ResourceManager.GetString("NextReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to Track.
        /// </summary>
        internal static string NothingToTrack {
            get {
                return ResourceManager.GetString("NothingToTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotificationCustomization.
        /// </summary>
        internal static string NotificationCustomization {
            get {
                return ResourceManager.GetString("NotificationCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Options.
        /// </summary>
        internal static string NotificationOptions {
            get {
                return ResourceManager.GetString("NotificationOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Threshold.
        /// </summary>
        internal static string NotificationThreshold {
            get {
                return ResourceManager.GetString("NotificationThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Drop Count.
        /// </summary>
        internal static string NumDrops {
            get {
                return ResourceManager.GetString("NumDrops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications can be clicked on to open the Duty Finder to the Raid category.
        /// </summary>
        internal static string OpenDutyFinderToRaid {
            get {
                return ResourceManager.GetString("OpenDutyFinderToRaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placed Stickets.
        /// </summary>
        internal static string PlacedStickers {
            get {
                return ResourceManager.GetString("PlacedStickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Has Book.
        /// </summary>
        internal static string PlayerHasBook {
            get {
                return ResourceManager.GetString("PlayerHasBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scored 80+.
        /// </summary>
        internal static string Plus80 {
            get {
                return ResourceManager.GetString("Plus80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raids (Alliance).
        /// </summary>
        internal static string RaidsAlliance {
            get {
                return ResourceManager.GetString("RaidsAlliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raids Available.
        /// </summary>
        internal static string RaidsAvailable {
            get {
                return ResourceManager.GetString("RaidsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of drops required from this duty to be considered complete.
        /// </summary>
        internal static string RaidsModuleHelp {
            get {
                return ResourceManager.GetString("RaidsModuleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raids (Normal).
        /// </summary>
        internal static string RaidsNormal {
            get {
                return ResourceManager.GetString("RaidsNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Time.
        /// </summary>
        internal static string RemainingTime {
            get {
                return ResourceManager.GetString("RemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This instance is available for a stamp if you re-roll it.
        /// </summary>
        internal static string RerollNotice {
            get {
                return ResourceManager.GetString("RerollNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} re-rolls available.
        /// </summary>
        internal static string RerollsAvailable {
            get {
                return ResourceManager.GetString("RerollsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Message.
        /// </summary>
        internal static string ResetMessage {
            get {
                return ResourceManager.GetString("ResetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roulettes Remaining.
        /// </summary>
        internal static string RoulettesRemaining {
            get {
                return ResourceManager.GetString("RoulettesRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Chance Points.
        /// </summary>
        internal static string SecondChancePoints {
            get {
                return ResourceManager.GetString("SecondChancePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message on Reset.
        /// </summary>
        internal static string SendMessageOnReset {
            get {
                return ResourceManager.GetString("SendMessageOnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends a notification to chat if a reset recently occured.
        /// </summary>
        internal static string SendMessageOnResetHelp {
            get {
                return ResourceManager.GetString("SendMessageOnResetHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Status on Login.
        /// </summary>
        internal static string SendStatusOnLogin {
            get {
                return ResourceManager.GetString("SendStatusOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends a status notification to chat when you login.
        /// </summary>
        internal static string SendStatusOnLoginHelp {
            get {
                return ResourceManager.GetString("SendStatusOnLoginHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Status on Zone Change.
        /// </summary>
        internal static string SendStatusOnZoneChange {
            get {
                return ResourceManager.GetString("SendStatusOnZoneChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends a status notification to chat when you change zones
        ///Limited to once per 5 mins.
        /// </summary>
        internal static string SendStatusOnZoneChangeHelp {
            get {
                return ResourceManager.GetString("SendStatusOnZoneChangeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        internal static string Show_All {
            get {
                return ResourceManager.GetString("Show All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Disabled.
        /// </summary>
        internal static string ShowDisabled {
            get {
                return ResourceManager.GetString("ShowDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle Available.
        /// </summary>
        internal static string ShuffleAvailable {
            get {
                return ResourceManager.GetString("ShuffleAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle Available Notice.
        /// </summary>
        internal static string ShuffleAvailableNotice {
            get {
                return ResourceManager.GetString("ShuffleAvailableNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warns when you are near the second chance limit and can shuffle your stickers.
        /// </summary>
        internal static string ShuffleAvailableNoticeHelp {
            get {
                return ResourceManager.GetString("ShuffleAvailableNoticeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Allowance Used.
        /// </summary>
        internal static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snooze.
        /// </summary>
        internal static string Snooze {
            get {
                return ResourceManager.GetString("Snooze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        internal static string Special {
            get {
                return ResourceManager.GetString("Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Tasks Label.
        /// </summary>
        internal static string SpecialTasksLabel {
            get {
                return ResourceManager.GetString("SpecialTasksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A stamp is already available for this instance.
        /// </summary>
        internal static string StampAlreadyAvailable {
            get {
                return ResourceManager.GetString("StampAlreadyAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can claim a stamp for this duty!.
        /// </summary>
        internal static string StampClaimable {
            get {
                return ResourceManager.GetString("StampClaimable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Message.
        /// </summary>
        internal static string StatusMessage {
            get {
                return ResourceManager.GetString("StatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Unknown.
        /// </summary>
        internal static string StatusUnknown {
            get {
                return ResourceManager.GetString("StatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticker Available.
        /// </summary>
        internal static string StickerAvailable {
            get {
                return ResourceManager.GetString("StickerAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticker Available Notice.
        /// </summary>
        internal static string StickerAvailableNotice {
            get {
                return ResourceManager.GetString("StickerAvailableNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When changing zones, warn if there are stickers available to claim.
        /// </summary>
        internal static string StickerAvailableNoticeHelp {
            get {
                return ResourceManager.GetString("StickerAvailableNoticeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Stickers Remaining.
        /// </summary>
        internal static string StickersRemaining {
            get {
                return ResourceManager.GetString("StickersRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppressed.
        /// </summary>
        internal static string Suppressed {
            get {
                return ResourceManager.GetString("Suppressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Data.
        /// </summary>
        internal static string TaskData {
            get {
                return ResourceManager.GetString("TaskData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Selection.
        /// </summary>
        internal static string TaskSelection {
            get {
                return ResourceManager.GetString("TaskSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks Incomplete.
        /// </summary>
        internal static string TasksIncomplete {
            get {
                return ResourceManager.GetString("TasksIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport.
        /// </summary>
        internal static string Teleport {
            get {
                return ResourceManager.GetString("Teleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleporting to &apos;{0}&apos;.
        /// </summary>
        internal static string TeleportingTo {
            get {
                return ResourceManager.GetString("TeleportingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Module.
        /// </summary>
        internal static string TestModule {
            get {
                return ResourceManager.GetString("TestModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Alignment.
        /// </summary>
        internal static string TextAlignment {
            get {
                return ResourceManager.GetString("TextAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Border Color.
        /// </summary>
        internal static string TextBorderColor {
            get {
                return ResourceManager.GetString("TextBorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Color.
        /// </summary>
        internal static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets Available.
        /// </summary>
        internal static string TicketsAvailable {
            get {
                return ResourceManager.GetString("TicketsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets Remaining.
        /// </summary>
        internal static string TicketsRemaining {
            get {
                return ResourceManager.GetString("TicketsRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Not Available.
        /// </summary>
        internal static string TimeNotAvailable {
            get {
                return ResourceManager.GetString("TimeNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Remaining.
        /// </summary>
        internal static string TimeRemaining {
            get {
                return ResourceManager.GetString("TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Until Mission Complete.
        /// </summary>
        internal static string TimeUntilMissionComplete {
            get {
                return ResourceManager.GetString("TimeUntilMissionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo Configuration.
        /// </summary>
        internal static string TodoConfiguration {
            get {
                return ResourceManager.GetString("TodoConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Todo Display.
        /// </summary>
        internal static string TodoDisable {
            get {
                return ResourceManager.GetString("TodoDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo Display Configuration.
        /// </summary>
        internal static string TodoDisplayConfiguration {
            get {
                return ResourceManager.GetString("TodoDisplayConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo Display Enable.
        /// </summary>
        internal static string TodoDisplayEnable {
            get {
                return ResourceManager.GetString("TodoDisplayEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Todo Display.
        /// </summary>
        internal static string TodoEnable {
            get {
                return ResourceManager.GetString("TodoEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Todo Display.
        /// </summary>
        internal static string TodoToggle {
            get {
                return ResourceManager.GetString("TodoToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasure Map.
        /// </summary>
        internal static string TreasureMap {
            get {
                return ResourceManager.GetString("TreasureMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tribal Quests.
        /// </summary>
        internal static string TribalQuests {
            get {
                return ResourceManager.GetString("TribalQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications can be clicked on to teleport to Ul&apos;dah.
        /// </summary>
        internal static string UldahTeleport {
            get {
                return ResourceManager.GetString("UldahTeleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        internal static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unclaimed Book Warning.
        /// </summary>
        internal static string UnclaimedBookWarning {
            get {
                return ResourceManager.GetString("UnclaimedBookWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreal Trial Available.
        /// </summary>
        internal static string UnrealTrialAvailable {
            get {
                return ResourceManager.GetString("UnrealTrialAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnSnooze.
        /// </summary>
        internal static string UnSnooze {
            get {
                return ResourceManager.GetString("UnSnooze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Allowance.
        /// </summary>
        internal static string WeeklyAllowance {
            get {
                return ResourceManager.GetString("WeeklyAllowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Tasks Label.
        /// </summary>
        internal static string WeeklyTasksLabel {
            get {
                return ResourceManager.GetString("WeeklyTasksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Limit.
        /// </summary>
        internal static string WeeklyTomestoneLimit {
            get {
                return ResourceManager.GetString("WeeklyTomestoneLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wondrous Tails.
        /// </summary>
        internal static string WondrousTails {
            get {
                return ResourceManager.GetString("WondrousTails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications can be clicked on to open the Wondrous Tails Book or teleport to Idlyshire.
        /// </summary>
        internal static string WondrousTailsClickableLink {
            get {
                return ResourceManager.GetString("WondrousTailsClickableLink", resourceCulture);
            }
        }
    }
}
